<?php
return [
  [
    'name' => 'mailing_template_category',
    'entity' => 'OptionGroup',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 3,
      'name' => 'mailing_template_category',
      'title' => 'Mailing Template Category',
      'description' => NULL,
      'data_type' => NULL,
      'is_reserved' => TRUE,
      'is_active' => TRUE,
      'is_locked' => FALSE,
    ],
  ],
  [
    'name' => 'mailing_template_category_newsletters',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 3,
      'option_group_id' => 'mailing_template_category',
      'label' => 'Newsletters',
      'value' => '1',
      'name' => 'newsletters',
      'grouping' => NULL,
      'filter' => 0,
      'is_default' => TRUE,
      'weight' => 1,
      'description' => NULL,
      'is_optgroup' => FALSE,
      'is_reserved' => FALSE,
      'is_active' => TRUE,
      'icon' => NULL,
      'color' => NULL,
      'component_id' => NULL,
      'visibility_id' => NULL,
    ],
  ],
  [
    'name' => 'mailing_template_category_legislative_announcements',
    'entity' => 'OptionValue',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 3,
      'option_group_id' => 'mailing_template_category',
      'label' => 'Legislative Announcements',
      'value' => '2',
      'name' => 'legislative_announcements',
      'grouping' => NULL,
      'filter' => 0,
      'is_default' => TRUE,
      'weight' => 1,
      'description' => NULL,
      'is_optgroup' => FALSE,
      'is_reserved' => FALSE,
      'is_active' => TRUE,
      'icon' => NULL,
      'color' => NULL,
      'component_id' => NULL,
      'visibility_id' => NULL,
    ],
  ],
];