<?php
require_once(dirname(__FILE__) . '/nyss_backup.php');

function nyss_backup_menu () {
	$items = array();

	$items['backupdata'] = array (
	    'title' => t('Backup/Restore Instance'),
	    'page callback' => 'nyss_backup_page',
	    'access arguments' => array('export print production files'),
	);

	return $items;
}

function nyss_backup_page() {
	if(get_data_dir()) {
		if($_GET['function']) {
			$app_functions = array(
				'instance_file_list' => 'nyss_backup_instance_file_list',
				'delete' => 'nyss_backup_delete_file',
				'backup' => 'nyss_backup_backup_file',
				'restore' => 'nyss_backup_restore_from_file',
			);

			$function = $_GET['function'];

			$data = array('error' => 'error');
			if($app_functions[$function]) {
				$data = call_user_func($app_functions[$function]);
			}

			header('Content-type: application/json');
			print json_encode($data);

			//prevent theme from rendering
			exit();
		}
		else {
			drupal_add_js(drupal_get_path('module','nyss_backup').'/js/tmpl.js');
			drupal_add_js(drupal_get_path('module','nyss_backup').'/js/nyss_backup.js');
			drupal_add_js(drupal_get_path('module','civicrm').'/../packages/jquery/jquery.js');
			drupal_add_css(drupal_get_path('module','nyss_backup').'/nyss_backup.css');
			include 'js/templates.html';
		
			return "";
		}
	}
	else {
		return "Please make sure that backup.ui.dirname "
			."is specified and that apache has write access to "
			."[data.rootdir]/[data_dirname]/[backup.ui.dirname]";
	}


}

function nyss_backup_instance_file_list() {
	return get_instance_files();
}

function nyss_backup_delete_file() {
	$file = $_GET['file'];
	return array('success' => do_delete($file));
}

function nyss_backup_backup_file() {
	$file_name = urldecode($_GET['file_name']);
	$file_time = urldecode($_GET['file_time']);
	return array('success' => do_backup($file_name, $file_time));
}

function nyss_backup_restore_from_file() {
	$file = $_GET['file'];
	return array('success' => do_restore($file));
}