<?php 
function nyss_import_civicrm_import( $object, $usage, &$objectRef, &$params ) {
	
	//during import, accept special tag_import column for processing
	$cType           = $objectRef->_contactType;
	$dupeType        = $objectRef->_onDuplicate;
	$contactID       = $params['contactID'];
	$importID        = $params['importID'];
	$importTempTable = $params['importTempTable'];
	$fields          = $params['fields'];
	
	require_once 'CRM/Core/DAO.php';
	
	//only proceed if tag_import exists in import
	if ( CRM_Core_DAO::checkFieldExists($importTempTable, 'tag_import') ) {
	
		$sqlTags = "SELECT tag_import
					FROM $importTempTable
					WHERE _id = $importID;";
		$taglist = CRM_Core_DAO::singleValueQuery( $sqlTags );
	
		if ( $taglist ) {
			require_once 'CRM/Core/BAO/EntityTag.php';
	
			$keywords = array();
			$keywords = explode( '|', $taglist );
	
			foreach ( $keywords as $keyword ) {
				$params = array(
          'version' => 3,
          'name' => $keyword,
          'parent_id' => '296'
        );
			
				//lookup tag; create new if nonexist
				$tag = civicrm_api('tag', 'getsingle', $params);
				if ( $tag['is_error'] ) {
					$tag = civicrm_tag_create($params);
					$tagid = $tag['tag_id'];
				} else {
					$tagid = $tag['id'];
				}
					
				//only add tag to contact if not already present
				$entityTags = CRM_Core_BAO_EntityTag::getTag($contactID);
				if ( !in_array($tagid, $entityTags) ) {
					$entityParams = array(
            'version' => 3,
            'tag_id' => $tagid,
            'contact_id' => $contactID
          );
					civicrm_api('entity_tag', 'create', $entityParams);
				}
			}
		}
	}
	
	/*//CRM_Core_Error::debug('us', $usage);
	//CRM_Core_Error::debug('ob', $objectRef);
	CRM_Core_Error::debug('tb', $importTempTable);
	CRM_Core_Error::debug('ii, $importIDs);
	//CRM_Core_Error::debug('fd', $fields);
	exit();*/

}
