// Generated by CoffeeScript 1.6.2
(function() {
  var Request, bbhg, _data, _functions, _packages, _settings;

  bbhg = (function() {
    function bbhg() {}

    bbhg.prototype.data = function(req) {
      var method, _i, _len, _ref, _results;

      _ref = req["methods"];
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        method = _ref[_i];
        _results.push(_data[method] = _functions[method.toLowerCase()].apply());
      }
      return _results;
    };

    return bbhg;

  })();

  _packages = {
    constructor: function() {
      return this.request = new Request();
    },
    getpackagesnames: function(aryobj) {
      return console.log(Object.keys(this));
    }
  };

  _functions = {
    getLocations: function(aryobj) {
      var locations;

      locations = {
        OPENLEG_BASE_URL: "http://open.nysenate.gov/legislation/search/"
      };
      return locations;
    },
    getUserData: function(aryobj) {}
  };

  Request = (function() {
    function Request() {}

    Request.prototype.queueRequests = function(req) {};

    Request.prototype.getRequests = function(req) {};

    return Request;

  })();

  _data = {};

  _settings = {
    requesting: true
  };

  if (window.bbUtils != null) {
    console.log(bbhg);
  } else {
    console.log("bbUtils needs to be declared first.");
  }

}).call(this);
