// Generated by CoffeeScript 1.6.3
(function() {
  var Request, hg, _data, _functions, _packages, _settings,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  hg = (function(_super) {
    __extends(hg, _super);

    function hg() {}

    hg.prototype.data = function(req) {
      var method, _i, _len, _ref, _results;
      _ref = req["methods"];
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        method = _ref[_i];
        _results.push(_data[method] = _functions[method.toLowerCase()].apply());
      }
      return _results;
    };

    return hg;

  })(bb);

  _packages = {
    constructor: function() {
      return this.request = new Request();
    },
    getpackagesnames: function(aryobj) {
      return console.log(Object.keys(this));
    }
  };

  _functions = {
    getLocations: function(aryobj) {
      var locations;
      locations = {
        OPENLEG_BASE_URL: "http://open.nysenate.gov/legislation/search/"
      };
      return locations;
    },
    getUserData: function(aryobj) {}
  };

  Request = (function() {
    function Request() {}

    Request.prototype.queueRequests = function(req) {};

    Request.prototype.getRequests = function(req) {};

    return Request;

  })();

  _data = {};

  _settings = {
    requesting: true
  };

  window["bbhg"] = new hg;

}).call(this);
