-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `nyss_inbox_attachments`;
DROP TABLE IF EXISTS `nyss_inbox_messages_matched`;
DROP TABLE IF EXISTS `nyss_inbox_messages`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * nyss_inbox_messages
-- *
-- * Metadata re: the inbound email
-- *
-- *******************************************************/
CREATE TABLE `nyss_inbox_messages` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique InboxMessages ID',
  `message_id` int COMMENT 'Email message ID',
  `imap_id` int COMMENT 'IMAP message ID',
  `sender_name` varchar(255) COMMENT 'Email from name',
  `sender_email` varchar(255) COMMENT 'Email from email',
  `subject` varchar(255),
  `body` longtext,
  `forwarder` varchar(255) COMMENT 'Individual who forwarded the email',
  `status` int COMMENT 'See constants in BAO',
  `matcher` int COMMENT 'See constants in BAO',
  `format` varchar(10) COMMENT 'plain/html',
  `debug` varchar(255) COMMENT 'Additional details useful for debugging.',
  `updated_date` datetime,
  `email_date` datetime,
  PRIMARY KEY (`id`),
  INDEX `idx_sender_email`(sender_email),
  INDEX `idx_status`(status),
  CONSTRAINT FK_nyss_inbox_messages_matcher FOREIGN KEY (`matcher`) REFERENCES `civicrm_contact`(`id`) ON DELETE SET NULL
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * nyss_inbox_messages_matched
-- *
-- * Links messages with matched contacts and activities
-- *
-- *******************************************************/
CREATE TABLE `nyss_inbox_messages_matched` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique InboxMessagesMatched ID',
  `row_id` int COMMENT 'FK to inbox row ID',
  `message_id` int COMMENT 'FK to inbox message ID',
  `matched_id` int COMMENT 'FK to matched contact ID',
  `activity_id` int COMMENT 'FK to activity ID',
  PRIMARY KEY (`id`),
  INDEX `idx_row_id`(row_id),
  INDEX `idx_message_id`(message_id),
  INDEX `idx_matched_id`(matched_id),
  INDEX `idx_activity_id`(activity_id),
  CONSTRAINT FK_nyss_inbox_messages_matched_row_id FOREIGN KEY (`row_id`) REFERENCES `nyss_inbox_messages`(`id`) ON DELETE SET NULL,
  CONSTRAINT FK_nyss_inbox_messages_matched_message_id FOREIGN KEY (`message_id`) REFERENCES `nyss_inbox_messages`(`message_id`) ON DELETE SET NULL,
  CONSTRAINT FK_nyss_inbox_messages_matched_matched_id FOREIGN KEY (`matched_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE SET NULL,
  CONSTRAINT FK_nyss_inbox_messages_matched_activity_id FOREIGN KEY (`activity_id`) REFERENCES `civicrm_activity`(`id`) ON DELETE SET NULL
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * nyss_inbox_attachments
-- *
-- * Store metadata re: email attachments.
-- *
-- *******************************************************/
CREATE TABLE `nyss_inbox_attachments` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique InboxAttachments ID',
  `email_id` int unsigned DEFAULT NULL COMMENT 'FK to InboxMessages',
  `file_name` varchar(255) DEFAULT NULL COMMENT 'File name',
  `file_full` varchar(512) DEFAULT NULL COMMENT 'Full path to file',
  `rejection` varchar(255) DEFAULT NULL COMMENT 'Details if attachment cannot be processed.',
  `mime_type` varchar(128) DEFAULT NULL,
  `size` int DEFAULT NULL,
  `ext` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT FK_nyss_inbox_attachments_email_id FOREIGN KEY (`email_id`) REFERENCES `nyss_inbox_messages`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;
