<?php

function nyss_imapper_init() {
	if (substr(request_path(),0,13) == "civicrm/imap/") {
	    //civicrm_initialize(); //Make sure to include jquery first
	    $module_path = drupal_get_path('module', 'nyss_imapper');
	    drupal_add_css($module_path.'/nyss_imapper.css');
	    drupal_add_css('./sites/default/themes/Bluebird/nyss_skin/tags/tags.css');
		  drupal_add_js($module_path.'/nyss_imapper.js');
	    drupal_add_js('/sites/default/themes/Bluebird/scripts/bbtree.js');
      // fixes nyss #7458
      drupal_add_js($module_path.'/jquery.dataTables-1.9.4.min.js');
      drupal_add_css($module_path.'/jquery.dataTables-1.9.4.css');
	}
}

function nyss_imapper_civicrm_xmlMenu( &$files ) {
    $files[] = dirname(__FILE__).DIRECTORY_SEPARATOR.'nyss_imapper.xml';
}

?>
