<?php
use CRM_NYSS_Case_ExtensionUtil as E;

// NYSS #17214
return [
  [
    'name' => 'SavedSearch_NYSS_Case_Search',
    'entity' => 'SavedSearch',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'NYSS_Case_Search',
        'label' => E::ts('NYSS Case Search'),
        'form_values' => [
          'join' => [
            'Case_CaseContact_Contact_01_Contact_RelationshipCache_Contact_01' => 'Case Manager',
            'Case_EntityTag_Tag_01' => 'Keword Tags',
            'Case_EntityTag_Tag_02' => 'Issue Code Tags',
          ],
        ],
        'api_entity' => 'Case',
        'api_params' => [
          'version' => 4,
          'select' => [
            'id',
            'subject',
            'case_type_id:label',
            'status_id:label',
            'GROUP_CONCAT(DISTINCT Case_CaseContact_Contact_01.display_name) AS GROUP_CONCAT_Case_CaseContact_Contact_01_display_name',
            'GROUP_CONCAT(DISTINCT Case_CaseContact_Contact_01_Contact_RelationshipCache_Contact_01.near_contact_id.display_name) AS GROUP_CONCAT_Case_CaseContact_Contact_01_Contact_RelationshipCache_Contact_01_near_contact_id_display_name',
            'is_deleted',
            'MIN(DISTINCT Case_CaseActivity_Activity_01.activity_date_time) AS MIN_Case_CaseActivity_Activity_01_activity_date_time',
            'GROUP_CONCAT(DISTINCT Case_CaseActivity_Activity_01.subject) AS GROUP_CONCAT_Case_CaseActivity_Activity_01_subject',
            'GROUP_FIRST(Case_CaseContact_Contact_01.id) AS GROUP_FIRST_Case_CaseContact_Contact_01_id',
          ],
          'orderBy' => [],
          'where' => [],
          'groupBy' => ['id', 'subject', 'case_type_id', 'status_id'],
          'join' => [
            [
              'Contact AS Case_CaseContact_Contact_01',
              'INNER',
              'CaseContact',
              [
                'id',
                '=',
                'Case_CaseContact_Contact_01.case_id',
              ],
            ],
            [
              'Contact AS Case_CaseContact_Contact_01_Contact_RelationshipCache_Contact_01',
              'LEFT',
              'RelationshipCache',
              [
                'Case_CaseContact_Contact_01.id',
                '=',
                'Case_CaseContact_Contact_01_Contact_RelationshipCache_Contact_01.far_contact_id',
              ],
              [
                'Case_CaseContact_Contact_01_Contact_RelationshipCache_Contact_01.case_id',
                '=',
                'id',
              ],
              [
                'Case_CaseContact_Contact_01_Contact_RelationshipCache_Contact_01.far_relation:name',
                '=',
                '"Case Manager is"',
              ],
              [
                'Case_CaseContact_Contact_01_Contact_RelationshipCache_Contact_01.is_current',
                '=',
                TRUE,
              ],
            ],
            [
              'Tag AS Case_EntityTag_Tag_01',
              'LEFT',
              'EntityTag',
              [
                'id',
                '=',
                'Case_EntityTag_Tag_01.entity_id',
              ],
              [
                'Case_EntityTag_Tag_01.entity_table',
                '=',
                '\'civicrm_case\'',
              ],
              [
                'Case_EntityTag_Tag_01.parent_id:name',
                '=',
                '"Keywords"',
              ],
            ],
            [
              'Tag AS Case_EntityTag_Tag_02',
              'LEFT',
              'EntityTag',
              [
                'id',
                '=',
                'Case_EntityTag_Tag_02.entity_id',
              ],
              [
                'Case_EntityTag_Tag_02.entity_table',
                '=',
                '\'civicrm_case\'',
              ],
              [
                'Case_EntityTag_Tag_02.parent_id:name',
                '=',
                '"Issue Codes"',
              ],
            ],
            [
              'Activity AS Case_CaseActivity_Activity_01',
              'LEFT',
              'CaseActivity',
              [
                'id',
                '=',
                'Case_CaseActivity_Activity_01.case_id',
              ],
              [
                'Case_CaseActivity_Activity_01.status_id:name',
                'IN',
                ['Scheduled', 'Open'],
              ],
              [
                'id',
                '=',
                'Case_CaseActivity_Activity_01.case_id',
              ],
            ],
          ],
          'having' => [],
        ],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'SavedSearch_NYSS_Case_Search_SearchDisplay_NYSS_Case_Search_Table_1',
    'entity' => 'SearchDisplay',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'NYSS_Case_Search_Table_1',
        'label' => E::ts('NYSS Case Search Table 1'),
        'saved_search_id.name' => 'NYSS_Case_Search',
        'type' => 'table',
        'settings' => [
          'description' => E::ts(NULL),
          'sort' => [
            ['start_date', 'DESC'],
          ],
          'limit' => 50,
          'pager' => [],
          'placeholder' => 5,
          'columns' => [
            [
              'type' => 'html',
              'key' => 'subject',
              'dataType' => 'String',
              'label' => E::ts('Case'),
              'sortable' => TRUE,
              'title' => E::ts('Manage Case'),
              'rewrite' => '<a href="/civicrm/contact/view/case?id=[id]&action=view&reset=1" target="_blank">#[id] &mdash; [subject]</a>',
            ],
            [
              'type' => 'field',
              'key' => 'GROUP_CONCAT_Case_CaseContact_Contact_01_display_name',
              'dataType' => 'String',
              'label' => E::ts('Constituent(s)'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'case_type_id:label',
              'dataType' => 'Integer',
              'label' => E::ts('Case Type'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'status_id:label',
              'dataType' => 'Integer',
              'label' => E::ts('Status'),
              'sortable' => TRUE,
              'editable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'GROUP_CONCAT_Case_CaseContact_Contact_01_Contact_RelationshipCache_Contact_01_near_contact_id_display_name',
              'dataType' => 'String',
              'label' => E::ts('Case Manager'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'html',
              'key' => 'MIN_Case_CaseActivity_Activity_01_activity_date_time',
              'dataType' => 'Timestamp',
              'label' => E::ts('Next Scheduled Activity'),
              'sortable' => TRUE,
              'format' => 'dateformatshortdate',
              'rewrite' => '{if $MIN_Case_CaseActivity_Activity_01_activity_date_time } [GROUP_CONCAT_Case_CaseActivity_Activity_01_subject] <em>({"[MIN_Case_CaseActivity_Activity_01_activity_date_time]"|date_format:"%b %d, %Y"})</em>{/if}',
            ],
            [
              'links' => [
                [
                  'entity' => 'Case',
                  'action' => 'view',
                  'join' => '',
                  'target' => '',
                  'icon' => 'fa-external-link',
                  'text' => E::ts('Manage'),
                  'style' => 'default',
                  'path' => '',
                  'task' => '',
                  'condition' => [],
                  'conditions' => [],
                ],
              ],
              'type' => 'links',
              'alignment' => 'text-right',
            ],
            [
              'text' => E::ts(''),
              'style' => 'default',
              'size' => 'btn-xs',
              'icon' => 'fa-bars',
              'links' => [
                [
                  'entity' => 'Case',
                  'action' => '',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-trash',
                  'text' => E::ts('Delete'),
                  'style' => 'danger',
                  'path' => '',
                  'task' => 'delete',
                  'condition' => [],
                  'conditions' => [],
                ],
                [
                  'path' => '/civicrm/contact/view/case/editClient?reset=1&action=update&id=[id]&cid=[GROUP_FIRST_Case_CaseContact_Contact_01_id]&context=search',
                  'icon' => 'fa-external-link',
                  'text' => E::ts('Assign to Another Constitutent'),
                  'style' => 'default',
                  'conditions' => [],
                  'task' => '',
                  'entity' => '',
                  'action' => '',
                  'join' => '',
                  'target' => '_blank',
                ],
              ],
              'type' => 'menu',
              'alignment' => 'text-right',
            ],
          ],
          'actions' => TRUE,
          'classes' => ['table', 'table-striped'],
          'actions_display_mode' => 'menu',
          'editableRow' => [
            'disable' => TRUE,
          ],
        ],
      ],
      'match' => [
        'saved_search_id',
        'name',
      ],
    ],
  ],
];
