<?php
use CRM_Contactlayout_ExtensionUtil as E;
return [
  'name' => 'ContactLayout',
  'table' => 'civicrm_contact_layout',
  'class' => 'CRM_Contactlayout_DAO_ContactLayout',
  'getInfo' => fn() => [
    'title' => E::ts('Contact Summary Layout'),
    'title_plural' => E::ts('Contact Summary Layouts'),
    'description' => E::ts('Layouts for the contact summary page'),
    'log' => TRUE,
    'add' => '1.0',
    'label_field' => 'label',
  ],
  'getFields' => fn() => [
    'id' => [
      'title' => E::ts('ID'),
      'sql_type' => 'int unsigned',
      'input_type' => 'Number',
      'required' => TRUE,
      'description' => E::ts('Unique ContactLayout ID'),
      'add' => '1.0',
      'primary_key' => TRUE,
      'auto_increment' => TRUE,
    ],
    'label' => [
      'title' => E::ts('Label'),
      'sql_type' => 'varchar(255)',
      'input_type' => 'Text',
      'required' => TRUE,
      'description' => E::ts('Name of this layout.'),
      'add' => '1.0',
    ],
    'contact_type' => [
      'title' => E::ts('Contact Type'),
      'sql_type' => 'varchar(255)',
      'input_type' => 'Select',
      'description' => E::ts('The type of contacts this layout applies to.'),
      'add' => '1.0',
      'pseudoconstant' => [
        'table' => 'civicrm_contact_type',
        'key_column' => 'name',
        'label_column' => 'label',
        'condition' => 'parent_id IS NULL',
      ],
    ],
    'contact_sub_type' => [
      'title' => E::ts('Contact Subtype'),
      'sql_type' => 'varchar(255)',
      'input_type' => 'Select',
      'description' => E::ts('The contacts subtypes this layout applies to.'),
      'add' => '1.0',
      'serialize' => constant('CRM_Core_DAO::SERIALIZE_SEPARATOR_BOOKEND'),
      'input_attrs' => [
        'multiple' => TRUE,
      ],
      'pseudoconstant' => [
        'table' => 'civicrm_contact_type',
        'key_column' => 'name',
        'label_column' => 'label',
        'condition' => 'parent_id IS NOT NULL',
      ],
    ],
    'groups' => [
      'title' => E::ts('Groups'),
      'sql_type' => 'varchar(255)',
      'input_type' => 'Select',
      'description' => E::ts('Show layout to users belonging to these groups.'),
      'add' => '1.0',
      'serialize' => constant('CRM_Core_DAO::SERIALIZE_SEPARATOR_BOOKEND'),
      'input_attrs' => [
        'multiple' => TRUE,
      ],
      'pseudoconstant' => [
        'table' => 'civicrm_group',
        'key_column' => 'id',
        'label_column' => 'title',
      ],
    ],
    'weight' => [
      'title' => E::ts('Order'),
      'sql_type' => 'int',
      'input_type' => 'Text',
      'add' => '1.0',
      'default' => 0,
    ],
    'blocks' => [
      'title' => E::ts('Blocks'),
      'sql_type' => 'longtext',
      'input_type' => 'TextArea',
      'required' => TRUE,
      'description' => E::ts('Contains json encoded layout blocks.'),
      'add' => '1.0',
      'serialize' => constant('CRM_Core_DAO::SERIALIZE_JSON'),
    ],
    'tabs' => [
      'title' => E::ts('Tabs'),
      'sql_type' => 'longtext',
      'input_type' => 'TextArea',
      'description' => E::ts('Contains json encoded layout tabs.'),
      'add' => '1.2',
      'serialize' => constant('CRM_Core_DAO::SERIALIZE_JSON'),
    ],
  ],
];
