// Generated by CoffeeScript 1.6.2
(function() {
  var BBTagLabel, View, getTrees, instance, parseTree, tree, typeIsArray, _ref, _treeData,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; },
    __slice = [].slice;

  tree = {
    startInstance: function(properties) {
      var initInstance, request;

      initInstance = new instance(properties);
      request = cj.when(getTrees.getRawJSON(initInstance));
      request.done(function(data) {
        getTrees.putRawJSON(data.message, initInstance);
        parseTree.init(initInstance);
        return initInstance.set('ready', true);
      });
      return initInstance;
    }
  };

  if ((_ref = window.jstree) == null) {
    window.jstree = tree;
  }

  getTrees = {
    getRawJSON: function(instance) {
      return cj.ajax(instance.get('callAjax'));
    },
    putRawJSON: function(data, instance) {
      return cj.each(data, function(i, tID) {
        var _ref1;

        if (_ref1 = parseFloat(tID.id), __indexOf.call(instance.get('dataSettings').pullSets, _ref1) >= 0) {
          return _treeData.rawData[tID.id] = {
            'name': tID.name,
            'children': tID.children
          };
        }
      });
    }
  };

  parseTree = {
    init: function(instance) {
      var _this = this;

      cj.each(_treeData.rawData, function(id, cID) {
        var tagName, _ref1;

        if (_ref1 = parseFloat(id), __indexOf.call(instance.get('dataSettings').pullSets, _ref1) >= 0) {
          _this.output = '';
          _this.tagLvl = 0;
          _this.setDataType(cID.name);
          _this.autocompleteID = [];
          _this.autocompleteName = [];
          _this.treeTop = id;
          tagName = new BBTagLabel(id);
          _this.addDLtop(tagName, cID.name, true);
          _this.addDTtag(tagName, cID.name);
          cj.each(cID.children, function(id, tID) {
            var childTagName;

            childTagName = new BBTagLabel(tID.id);
            _this.addDLtop(childTagName, tID.name);
            return _this.writeOutputData(tID);
          });
          _this.addDLbottom();
          return _this.writeData();
        }
      });
      return console.log("Loaded Data");
    },
    isItemMarked: function(value, type) {
      if (value(true)) {
        return type;
      } else {
        return '';
      }
    },
    isItemChildless: function(childLength) {
      if (childLength > 0) {
        return 'treeButton';
      } else {
        return '';
      }
    },
    writeOutputData: function(tID, parentTag) {
      var tagName,
        _this = this;

      tagName = new BBTagLabel(tID.id);
      this.addAutocompleteEntry(tID.id, tID.name);
      this.addDTtag(tagName, tID.name, parentTag);
      if (tID.children.length > 0) {
        cj.each(tID.children, function(id, cID) {
          var childTagName;

          childTagName = new BBTagLabel(cID.id);
          _this.addDLtop(childTagName, cID.name);
          return _this.writeOutputData(cID, tID.id);
        });
        return this.addDLbottom();
      } else {
        return this.addDLbottom();
      }
    },
    addDLtop: function(tagName, name, except) {
      if (!except) {
        this.tagLvl++;
      }
      return this.output += "<dl class='lv-" + this.tagLvl + "' id='" + (tagName.addDD()) + "' data-name='" + name + "'>";
    },
    addDTtag: function(tagName, name, parentTag) {
      if (parentTag == null) {
        parentTag = this.treeTop;
      }
      this.output += "<dt class='lv-" + this.tagLvl + " " + this.tagType + "-" + (tagName.passThru()) + "' id='" + (tagName.add()) + "' data-tagid='" + (tagName.passThru()) + "' data-name='" + name + "' data-parentid='" + parentTag + "'>";
      this.output += "<div class='tag'><span class='name'>" + name + "</span></div>";
      return this.output += "</dt>";
    },
    addDLbottom: function() {
      this.tagLvl--;
      return this.output += "</dl>";
    },
    setDataType: function(name) {
      switch (name) {
        case "Issue Code":
          return this.tagType = "issueCode";
        case "Positions":
          return this.tagType = "position";
        case "Keywords":
          return this.tagType = "keyword";
        default:
          return this.tagType = "tag";
      }
    },
    addAutocompleteEntry: function(id, name) {
      this.autocompleteID.push(id);
      return this.autocompleteName.push(name);
    },
    writeData: function() {
      _treeData.autocomplete[this.treeTop] = {
        'name': this.autocompleteName,
        'id': this.autocompleteID
      };
      return _treeData.html[this.treeTop] = this.output;
    }
  };

  _treeData = {
    autocomplete: {},
    rawData: {},
    html: {}
  };

  instance = (function() {
    function instance() {
      var callAjax, dataSettings, displaySettings, k, onSave, pageElements, properties, ready, v, _ref1,
        _this = this;

      properties = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      pageElements = {
        init: '.JSTreeInit',
        wrapper: '.JSTreeContainer',
        tagHolder: '.JSTree',
        messageHandler: '.JSMessages',
        tabLocation: '.JSTree-Tags',
        location: ''
      };
      onSave = false;
      ready = false;
      dataSettings = {
        pullSets: [291, 296, 292],
        contact: 0
      };
      displaySettings = {
        defaultTree: 291,
        mode: 'edit',
        fullSize: true,
        autocomplete: true,
        print: true,
        showActive: true
      };
      callAjax = {
        url: '/civicrm/ajax/tag/tree',
        data: {
          entity_type: 'civicrm_contact',
          entity_id: 0,
          call_uri: window.location.href,
          entity_counts: 0
        },
        dataType: 'json'
      };
      _ref1 = properties[0];
      for (k in _ref1) {
        v = _ref1[k];
        switch (k) {
          case "pageElements":
            pageElements = v;
            break;
          case "onSave":
            onSave = v;
            break;
          case "dataSettings":
            dataSettings = v;
            break;
          case "displaySettings":
            displaySettings = v;
            break;
          case "callAjax":
            callAjax = v;
            break;
          case "ready":
            ready = v;
        }
      }
      this.get = function(name) {
        var getRet;

        getRet = {};
        if ('pageElements' === name) {
          cj.extend(true, getRet, pageElements);
        }
        if ('onSave' === name) {
          return onSave;
        }
        if ('dataSettings' === name) {
          cj.extend(true, getRet, dataSettings);
        }
        if ('displaySettings' === name) {
          cj.extend(true, getRet, displaySettings);
        }
        if ('callAjax' === name) {
          cj.extend(true, getRet, callAjax);
        }
        if ('ready' === name) {
          return ready;
        }
        return getRet;
      };
      this.set = function(name, obj) {
        if ('pageElements' === name) {
          cj.extend(true, pageElements, obj);
        }
        if ('onSave' === name) {
          onSave = obj;
        }
        if ('dataSettings' === name) {
          cj.extend(true, dataSettings, obj);
        }
        if ('displaySettings' === name) {
          cj.extend(true, displaySettings, obj);
        }
        if ('callAjax' === name) {
          cj.extend(true, callAjax, obj);
        }
        if ('ready' === name) {
          return ready = obj;
        }
      };
    }

    return instance;

  })();

  typeIsArray = Array.isArray || function(value) {
    return {}.toString.call(value) === '[object Array]';
  };

  BBTagLabel = (function() {
    function BBTagLabel(tagID) {
      this.tagID = tagID;
    }

    BBTagLabel.prototype.add = function() {
      return "tagLabel_" + this.tagID;
    };

    BBTagLabel.prototype.remove = function() {
      return this.tagID.replace("tagLabel_", "");
    };

    BBTagLabel.prototype.addDD = function() {
      return "tagDropdown_" + this.tagID;
    };

    BBTagLabel.prototype.removeDD = function() {
      return this.tagID.replace("tagDropdown_", "");
    };

    BBTagLabel.prototype.passThru = function() {
      return this.tagID;
    };

    return BBTagLabel;

  })();

  window.jstree.views = {
    createNewView: function(instance) {
      var newView;

      return newView = new View(instance);
    }
  };

  View = (function() {
    function View(instance) {
      this.instance = instance;
      this.writeContainers();
      this.interval = this.setUpdateInterval(1000);
    }

    View.prototype.getData = function() {
      if (this.instance.get('ready') === true) {
        return this.killUpdateInterval(this.interval);
      }
    };

    View.prototype.setUpdateInterval = function(timeSet) {
      var callback,
        _this = this;

      callback = function() {
        return _this.getData();
      };
      return setInterval(callback, timeSet);
    };

    View.prototype.killUpdateInterval = function(clearInt) {
      return clearInterval(clearInt);
    };

    View.prototype.writeContainers = function() {
      var initInstances;

      this.pageElements = this.instance.get('pageElements');
      initInstances = cj(this.pageElements.init);
      return console.log(initInstances);
    };

    return View;

  })();

}).call(this);
