// Generated by CoffeeScript 1.6.2
(function() {
  var bbUtils, _ref, _settings;

  bbUtils = {
    localStorage: function(key, value) {
      var extended, parsedKV, unparsedKV;

      if (!localStorage) {
        return false;
      }
      if (value != null) {
        if (this.isJsonString(value)) {
          value = JSON.parse(value);
        } else {

        }
        unparsedKV = localStorage.getItem(key);
        if (unparsedKV == null) {
          unparsedKV = {};
        }
        if (this.isJsonString(unparsedKV)) {
          parsedKV = JSON.parse(unparsedKV);
        } else {
          parsedKV = unparsedKV;
        }
        extended = cj.extend({}, parsedKV, value);
        localStorage.setItem(key, JSON.stringify(extended));
        return true;
      } else {
        return JSON.parse(localStorage.getItem(key));
      }
    },
    isJsonString: function(str) {
      var e;

      try {
        JSON.parse(str);
      } catch (_error) {
        e = _error;
        return false;
      }
      return true;
    },
    version: function() {
      return _settings.version;
    }
  };

  _settings = {
    version: "0.0.1"
  };

  if ((_ref = window.bbUtils) == null) {
    window.bbUtils = bbUtils;
  }

}).call(this);
