<h3>This page is generated by CRM/SAGE/Page/SageTest.php</h3>

{foreach name=outer from=$tests item=test}
    <h3>{$test.name}</h3>
    <div class="status">
        {assign var='output' value=$test.out}
        {assign var='ret' value=$test.ret}
        <p>Call Returned: {$ret}</p>
        {foreach from=$output key=key item=val}
            {if ! is_array($val) }
                <strong>{$key}</strong>: <span style="white-space: pre-wrap">{$val}</span><br/>
            {/if}
        {/foreach}
    </div>
{/foreach}
