<?php 
function nyss_contactlistquery_civicrm_contactListQuery( &$query, $name, $context, $id ) {

//echo $query;


	//office staff group ID to use for activity assignees and case roles
	$groupID = '3';
	
	//LCD - limit activity assignees to office staff group
    if ( $context == 'activity_assignee' && $groupID ) {

		$query = str_replace("\n", " ", $query);
        $splitQuery = explode(" ",$query);
        $selectClause = $fromClause = $whereClause = $orderByClause = null ;
        $select = $from = $where = null;
        foreach( $splitQuery as $key => $value ) {
            if( !strcasecmp( $value , 'SELECT')) {
                continue;
            }
            if( !strcasecmp( $value , 'FROM')) {
                $select = true;
                continue;
            } 
            if( !strcasecmp( $value , 'WHERE')) { 
                $from = true;
                continue;
            }
            if( !strcasecmp( $value , 'ORDER')) { 
                $where = true;
            }
            if( !$select ) {
                $selectClause = $selectClause.' '.$value;
            } else if( !$from ) {
                $fromClause = $fromClause.' '.$value;
            } else if( !$where){
                $whereClause = $whereClause.' '.$value;
            } else {
                $orderByClause = $orderByClause.' '.$value;
            }
        }      

        $fromClause .= " INNER JOIN civicrm_group_contact cgc ON cgc.contact_id = cc.id ";
        $whereClause = " ($whereClause) AND cgc.group_id IN ($groupID) AND cgc.status = 'Added'";   
        $query = "SELECT $selectClause FROM $fromClause WHERE $whereClause $orderByClause";

    } elseif ( $context == 'caseview' && $groupID ) { //case roles
		$query = "SELECT id, data 
				  FROM (
				   	SELECT cc.id as id, CONCAT_WS( ' :: ', sort_name, email ) as data, sort_name
				   	FROM civicrm_contact cc 
					  LEFT JOIN civicrm_email eml ON ( cc.id = eml.contact_id AND eml.is_primary = 1 )  
					  LEFT JOIN civicrm_address sts ON ( cc.id = sts.contact_id AND sts.is_primary = 1 )
					  INNER JOIN civicrm_group_contact cgc ON cgc.contact_id = cc.id     
					WHERE sort_name LIKE '%$name%' 
					  AND cc.is_deleted = 0 
					  AND cgc.group_id IN ($groupID)
					  AND cgc.status = 'Added'
   					LIMIT 0, 10
     			  ) t
				  ORDER BY sort_name";
	}
	
    return $query;

}

function nyss_contactlistquery_civicrm_buildForm( $formName, &$form ) {

	//Limit case roles available to add new role dialog to only those that apply to cases
	if ( $formName=='CRM_Case_Form_CaseView' ) {

		$caserelationships = array( '13' => 'Case Manager is',
									'8'  => 'Case Coordinator is',
									'15' => 'Support Staff is',
									'14' => 'Non-District Staff is'
								  );
		$form->add('select', 'role_type',  ts( 'Relationship Type' ), array( '' => ts( '- select type -' ) ) + $caserelationships );

	}
	
	//Limit import file size to 1MB
	if ( $formName =='CRM_Import_Form_DataSource' ) {
		
		$uploadFileSize = 1048576;
        $uploadSize = round(($uploadFileSize / (1024*1024)), 2);
        $form->assign('uploadSize', $uploadSize);
		$form->add('file', 'uploadFile', ts('Import Data File'), 'size=30 maxlength=60', true);
        
		$form->setMaxFileSize($uploadFileSize);
        $form->addRule('uploadFile', ts('File size should be less than %1 MBytes (%2 bytes)', array(1 => $uploadSize, 2 => $uploadFileSize)), 'maxfilesize', $uploadFileSize);
        $form->addRule('uploadFile', ts('Input file must be in CSV format'), 'utf8File');
        $form->addRule('uploadFile', ts('A valid file must be uploaded.'), 'uploadedfile');
		$form->_rules['uploadFile'][1]['message'] = 'File size should be less than 1 MBytes (1048576 bytes)';

	}
	
} //close buildForm
