<?php

function nyss_civihooks_menu()
{
  $items = [];
  $items['nyss_getfile'] = [
    'title' => t('NYSS Retrieve file'),
    'page callback' => 'nyss_civihooks_getfile',
    'access arguments' => ['export print production files'],
    'type' => MENU_SUGGESTED_ITEM,
  ];
  return $items;
} // nyss_civihooks_menu()


function nyss_civihooks_menu_alter(&$items) {
  //5253
  $items['admin/user/user/create']['access arguments'] = ['create users'];

  //7264 remove view tab
  $items['user/%']['type'] = MENU_CALLBACK;
} // nyss_civihooks_menu_alter()


function nyss_civihooks_form_alter(&$form, &$form_state, $form_id) {
  //watchdog('bluebird', 'form_id: <pre>'.print_r($form_id, TRUE).'</pre>');
  //watchdog('bluebird', 'form: <pre>'.print_r($form, TRUE).'</pre>');
  //watchdog('bluebird', 'form_state: <pre>'.print_r($form_state, TRUE).'</pre>');

  //6062/11725
  if ($form_id == 'user_profile_form') {
    $form['actions']['cancel']['#value'] = 'Delete User Account';
    $form['account']['name']['#description'] = '';
    $form['account']['mail']['#description'] = '';
    $form['account']['name']['#disabled'] = 1;
    unset($form['account']['pass']);

    //inject js because the role modifications below don't work for non-super-admins
    $form['#attached']['js'] = [
      drupal_get_path('module', 'nyss_civihooks') . '/js/user_profile_form.js',
    ];

    //roles
    $form['account']['roles']['#title'] = 'Assignable Roles';
    unset($form['account']['roles'][2]);

    $form['account']['roles'][9]['#prefix'] = '
      <div class="nyss-roles-section-header">Main Role</div>
      <div class="nyss-roles-description">In order for a staff member to get started in Bluebird, they must first have ONE main role assigned to them.</div>
    ';
    $form['account']['roles'][16]['#prefix'] = '
      <div class="nyss-roles-section-header">Add-on Roles</div>
      <div class="nyss-roles-description">Additional roles to extend access in specific feature areas.</div>
      <div class="nyss-roles-subsection-header">Bluebird Mass Email</div>
    ';
    $form['account']['roles'][19]['#prefix'] = '
      <div class="nyss-roles-subsection-header">Bluebird Inbound Email</div>
    ';
    $form['account']['roles'][8]['#prefix'] = '
      <div class="nyss-roles-section-header">Other Senate Office Roles</div>
      <div class="nyss-roles-description">Several Senate central staff offices have permission to access your Senator\'s Bluebird database. The roles below are used specifically for those offices.</div>
    ';
    $form['account']['roles'][4]['#prefix'] = '
      <div class="nyss-roles-section-header">Administrator Roles</div>
    ';

    $form['#submit'][] = 'nyss_civihooks_user_profile_form_submit';
  }

  if ($form_id == 'user_cancel_confirm_form') {
    unset($form['user_cancel_method']['user_cancel_block']);
    unset($form['user_cancel_method']['user_cancel_block_unpublish']);
    unset($form['user_cancel_method']['user_cancel_reassign']);
    $form['user_cancel_method']['user_cancel_delete']['#default_value'] = 'user_cancel_delete';
    $form['user_cancel_method']['user_cancel_delete']['#title'] = 'Delete the user account.';
    $form['user_cancel_method']['#title'] = '';

    unset($form['user_cancel_confirm']);
    $form['description']['#markup'] = 'Please confirm you wish to delete this account.';
    $form['actions']['submit']['#value'] = 'Delete User Account';

    $username = $form['_account']['#value']->name;
    $title = "Are you sure you want to delete the account: {$username}?";
    drupal_set_title($title);
  }

  //6055
  if ($form_id == 'user_admin_account') {
    unset($form['options']['operation']['#options']['cancel']);
  }

  //6740 make sure destination redirect includes query params
  if ($form_id == 'user_login_block') {
    $urlBase = drupal_get_destination();
    $urlQueryParams = drupal_get_query_parameters();
    unset($urlQueryParams['destination']);
    $urlQuery = drupal_http_build_query($urlQueryParams);
    $urlBase['destination'] = $urlBase['destination'].'?'.$urlQuery;
    $form['#action'] = url(current_path(), array('query' => $urlBase, 'external' => false));
  }

  //watchdog('bluebird', 'form (after hook): <pre>'.print_r($form, TRUE).'</pre>');
} // nyss_civihooks_form_alter()

function nyss_civihooks_page_alter(&$page)
{
  //dpm($page);
  $curPage = current_path();
  if ($curPage == 'admin/people') {
    $title = "Manage Users";
    drupal_set_title($title);

    //6709 only show permission filter if admin
    global $user;
    if (!in_array('Administrator', $user->roles) && !in_array('Superuser', $user->roles)) {
      unset($page['content']['system_main']['user_filter_form']['filters']['status']['filters']['permission']);
    }
  }
  elseif (strpos($curPage, 'user/') !== false) {
    $title = "Edit User";
    drupal_set_title($title);
  }
} // nyss_civihooks_page_alter()


function nyss_civihooks_permission() {
  return [
    'export print production files' => [
      'title' => t('Bluebird: Export Print Production Files'),
    ],
    'delete contacts permanently' => [
      'title' => t('Bluebird: Permanently Delete Contacts'),
    ],
    'administer district' => [
      'title' => t('Bluebird: Access District Admin Tasks'),
    ],
    'import print production' => [
      'title' => t('Bluebird: Access Print Production Import Tool'),
    ],
    'administer inbox polling' => [
      'title' => t('Bluebird: Access Inbox Polling'),
    ],
  ];
}


function nyss_civihooks_getfile()
{
  civicrm_initialize();
  $config =& CRM_Core_Config::singleton();

  $file = $_REQUEST['file'];
  $fullpath = $config->uploadDir.'printProduction/'.$file;

  if (!file_exists($fullpath) || !$file) {
    echo "No file provided. Make sure you have entered the full URL.<br />";
    exit();
  }

  $headers = array(
    "Pragma: public",
    "Expires: 0",
    "Cache-Control: no-cache,must-revalidate, post-check=0, pre-check=0",
    "Cache-Control: public",
    "Content-Description: File Transfer",
    "Content-Type: application/csv",
    "Content-Disposition: attachment; filename=".basename($fullpath),
    "Expires: Mon, 26 Jul 1997 05:00:00 GMT",
    'Content-Length: '.filesize($fullpath)
  );

  //don't use this, seems to cause problems...
  //file_transfer($fullpath, $headers);

  //spit out the header
  foreach ($headers as $header) {
    header($header);
  }

  $fh = fopen($fullpath, "r");

  if (!$fh) {
    echo "no file provided. file requested is: $fullpath";
    exit;
  }

  while (!feof($fh)) {
    echo fread($fh, 1024);
    ob_flush();
  }
  fclose($fh);
} // nyss_civihooks_getfile()

function nyss_civihooks_user_profile_form_submit($form, &$form_state) {
  //watchdog('bluebird', 'form: <pre>'.print_r($form, TRUE).'</pre>');
  //watchdog('bluebird', 'form_state: <pre>'.print_r($form_state, TRUE).'</pre>');

  if ($form_state['clicked_button']['#value'] == 'Save') {
    \Civi\Api4\System::flush(FALSE)->execute();
  }
}

// NYSS 5581
function nyss_civihooks_custom_theme() {
  $allowedPaths = [
    'civicrm/nyss/subscription/manage',
    'civicrm/nyss/subscription/view',
    'civicrm/nyss/subscription/expired',
  ];

  if (in_array($_GET['q'], $allowedPaths)) {
    return 'BluebirdPublic';
  }
  else {
    return null;
  }
}
