<?php

/*
 +--------------------------------------------------------------------+
 | CiviCRM version 3.4                                                |
 +--------------------------------------------------------------------+
 | Copyright CiviCRM LLC (c) 2004-2009                                |
 +--------------------------------------------------------------------+
 | This file is a part of CiviCRM.                                    |
 |                                                                    |
 | CiviCRM is free software; you can copy, modify, and distribute it  |
 | under the terms of the GNU Affero General Public License           |
 | Version 3, 19 November 2007.                                       |
 |                                                                    |
 | CiviCRM is distributed in the hope that it will be useful, but     |
 | WITHOUT ANY WARRANTY; without even the implied warranty of         |
 | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               |
 | See the GNU Affero General Public License for more details.        |
 |                                                                    |
 | You should have received a copy of the GNU Affero General Public   |
 | License along with this program; if not, contact CiviCRM LLC       |
 | at info[AT]civicrm[DOT]org. If you have questions about the        |
 | GNU Affero General Public License or the licensing of CiviCRM,     |
 | see the CiviCRM license FAQ at http://civicrm.org/licensing        |
 +--------------------------------------------------------------------+
*/

/**
 *
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2009
 * $Id$
 *
 */

  /**
   * freeeze address fields of location type 'Board Of Election' on contact edit form
   *
   * @return void
   * @access public
   */

function nyss_boe_civicrm_buildForm( $formName, &$form ) 
{    
  if ( $formName == 'CRM_Contact_Form_Contact' ) {

    //do not allow to edit as well as set 'Board of Election' loc type.
    require_once 'CRM/Utils/Request.php';
    require_once 'CRM/Core/BAO/Preferences.php';
    $blocks = array(
      'Email' => 'email',
      'Phone' => 'phone',
      'IM' => 'im',
      'OpenID' => 'openid',
      'Address' => 'address'
    );

    $blockId = CRM_Utils_Request::retrieve( 'count', 'Positive', CRM_Core_DAO::$_nullObject );
    $blockName = CRM_Utils_Request::retrieve( 'block', 'String', CRM_Core_DAO::$_nullObject );
    $values = $form->_values;
    if ( !empty( $_POST ) ) $values = $_POST;

    $locationTypes = CRM_Core_PseudoConstant::get('CRM_Core_DAO_Address', 'location_type_id');
    $boardOfElectionId = array_search('BOE', $locationTypes);

    $addressOptions = $form->get( 'addressOptions' );
    if ( !isset( $addressOptions ) ) {
      $addressOptions = CRM_Core_BAO_Setting::valueOptions(CRM_Core_BAO_Setting::SYSTEM_PREFERENCES_NAME,
        'address_options', TRUE, NULL, TRUE
      );
      $form->set( 'addressOptions', $addressOptions );
    }

    //its a first block.
    if ( !$blockId ) $blockId = 1;
    foreach ( $blocks as $label => $name ) {
      if ( ($blockId != 1) && ($blockName != $label ) ) {
        continue;
      }
      $freezeElement = $unsetOption = false;
      if ( CRM_Utils_Array::value( $name, $values ) && is_array( $values[$name] ) &&
        $boardOfElectionId == CRM_Utils_Array::value( 'location_type_id',
                                                      $values[$name][$blockId] ) ) {
        $freezeElement = true;
      }
      else {
        $unsetOption = true;
      }

      if ( $name == 'address' ) {
        foreach ( $addressOptions as $key => $value ) {
          if ( empty( $value ) ) {
            continue;
          }
          if ( in_array( $key, array( 'country', 'state_province' ) ) && $freezeElement ) {
            $key .= '_id';

            //we might registered duplicate elements.
            if ( $key == 'state_province_id' ) {
              if ( array_key_exists( "address[$blockId][$key]", $form->_duplicateIndex ) ) {
                $duplicateIndexes = $form->_duplicateIndex["address[$blockId][$key]"];
                foreach ( $duplicateIndexes as $index ) {
                  $element = $form->_elements[$index];
                  $element->freeze( );
                }
              }
            }
          }

          //process address data element.
          _civicrm_processElement( $form, "address[$blockId][$key]", $freezeElement );
        }
        //hide 'Use Household Address' if location type is 'Board Of Election'
        //c3.3 update for shared address element
        //NYSS 5505 - added call to elementExists, or else it could throw an error when
        //            trying to dremove an element that doesn't exist.
        if ( $blockId == 1 && $freezeElement && $form->elementExists( 'address[1][use_shared_address]' ) ) {
          $form->removeElement( 'address[1][use_shared_address]' );
        }
      }
      else {
        $dataElementName = "{$name}[$blockId][$name]";
        if ( $name == 'im' ) {
          $dataElementName = "{$name}[$blockId][name]";
          _civicrm_processElement( $form, "{$name}[$blockId][provider_id]", $freezeElement );
        }
        else if ( $name == 'phone' ) {
          _civicrm_processElement( $form, "{$name}[$blockId][phone_type_id]", $freezeElement );
        }

        //process data element.
        _civicrm_processElement( $form, $dataElementName, $freezeElement );
      }

      //process loc type element.
      _civicrm_processElement( $form, "{$name}[$blockId][location_type_id]", $freezeElement, $unsetOption );
    }
  }

  $inlineBlockBOE = array(
    'CRM_Contact_Form_Inline_Email',
    'CRM_Contact_Form_Inline_Phone',
    'CRM_Contact_Form_Inline_Address',
  );

  if ( in_array($formName, $inlineBlockBOE) ) {
    $locationTypes = CRM_Core_PseudoConstant::get('CRM_Core_DAO_Address', 'location_type_id');
    $boardOfElectionId = array_search('BOE', $locationTypes);

    //determine name and object
    switch ($formName) {
      case 'CRM_Contact_Form_Inline_Email':
        $name    = 'email';
        $objName = '_emails';
        break;
      case 'CRM_Contact_Form_Inline_Phone':
        $name    = 'phone';
        $objName = '_phones';
        break;
      case 'CRM_Contact_Form_Inline_Address':
        $name    = 'address';
        $objName = '_addresses';
        break;
    }

    $excludeFlds = array(
      'is_primary',
    );

    $b = 0;
    foreach ( $form->_defaultValues[$name] as $blockId => $block ) {
      //CRM_Core_Error::debug_var('block', $block);
      //CRM_Core_Error::debug_var('elements', $form->_elementIndex);
      if ( $block['location_type_id'] == $boardOfElectionId ) {
        $elementLoc = "{$name}[$blockId][location_type_id]";
        if ( !$form->elementExists( $elementLoc ) ) {
          continue;
        }

        $elementName = "{$name}[$blockId]";

        foreach ( $form->_elementIndex as $ele => $dontcare ) {
          if ( strpos($ele, $elementName) === 0 ) {
            $fld = trim(str_replace($elementName, '', $ele),'[]');
            //CRM_Core_Error::debug_var('$fld', $fld);
            if ( !in_array($fld, $excludeFlds) && strpos($fld, 'custom_') === FALSE ) {
              $element = $form->getElement( $ele );
              $element->freeze();
            }
          }
        }
      }
      $b++;
    }
    $b = ($b < 5) ? 5 : $b;

    //suppress special location type options
    for ( $i = 1; $i <= $b; $i++ ) {
      $elementLoc = "{$name}[$i][location_type_id]";
      if ( ! $form->elementExists( $elementLoc ) ) {
        continue;
      }
      $eleLoc =& $form->getElement( $elementLoc );
      $specialTypes = array('BOE', 'Billing', 'NCOA');
      foreach ( $eleLoc->_options as $index => $options ) {
        if ( in_array($options['text'], $specialTypes) &&
          ! $eleLoc->_flagFrozen
        ) {
          unset($eleLoc->_options[$index]);
        }
      }
      //reset array keys or we have issues with the display
      $eleLoc->_options = array_values($eleLoc->_options);
    }
    //CRM_Core_Error::debug_var('form',$form);
  }
}

/**
 * process the elements on the form
 *
 * @return void
 * @access public
 */
function _civicrm_processElement( &$form, $elementName, $freezeElement = false, $unsetOption = false ) 
{
  if ( ! $form->elementExists( $elementName ) ) {
    return false;
  }

  $element = $form->getElement( $elementName );
  if ( $freezeElement ) {
    $element->freeze( );
  }

  if ( $unsetOption ) {
    $newOptions = array();
    foreach ( $element->_options as $index => $options ) {
      if ( $options['text'] != 'BOE' &&
        $options['text'] != 'Billing' &&
        $options['text'] != 'NCOA'
      ) {
        $newOptions[] = $element->_options[$index];
      }
    }
    $element->_options = $newOptions;
  }
}
