// Generated by CoffeeScript 1.6.3
(function() {
  var Instance, Node, Tree, View, getTrees, jstree, setProp, _utils,
    __slice = [].slice,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; },
    _this = this;

  Function.prototype.property = function(prop, desc) {
    return Object.defineProperty(this.prototype, prop, desc);
  };

  jstree = {
    init: function(settings, view) {
      var instance, pageElements, request,
        _this = this;
      instance = new Instance();
      setProp(settings, instance);
      pageElements = instance.get("pageElements");
      view["exec"].call(this, instance);
      cj(pageElements.wrapper).data("isLoading", true);
      request = cj.when(getTrees.getRawJSON(instance));
      request.done(function(data) {
        getTrees.putRawJSON(data.message, instance);
        cj(pageElements.wrapper).data("isLoading", false);
        return view["done"].call(_this, instance);
      });
      return instance;
    }
  };

  setProp = function() {
    var instance, k, properties, v, _i, _ref, _results;
    properties = 2 <= arguments.length ? __slice.call(arguments, 0, _i = arguments.length - 1) : (_i = 0, []), instance = arguments[_i++];
    _ref = properties[0];
    _results = [];
    for (k in _ref) {
      v = _ref[k];
      _results.push(instance.set(k, v));
    }
    return _results;
  };

  getTrees = {
    getRawJSON: function(instance) {
      return cj.ajax(instance.get('callAjax'));
    },
    putRawJSON: function(data, instance) {
      var rawData;
      rawData = {};
      cj.each(data, function(i, tID) {
        var _ref;
        if (_ref = parseFloat(tID.id), __indexOf.call(instance.get('dataSettings').pullSets, _ref) >= 0) {
          return rawData[tID.id] = {
            'name': tID.name,
            'children': tID.children
          };
        }
      });
      return instance.rawData = rawData;
    }
  };

  Instance = (function() {
    function Instance(_rawData, _autocomplete, _treeNames, _trees) {
      var callAjax, dataSettings, displaySettings, onSave, pageElements,
        _this = this;
      this._rawData = _rawData;
      this._autocomplete = _autocomplete;
      this._treeNames = _treeNames;
      this._trees = _trees;
      pageElements = {
        init: 'JSTreeInit',
        wrapper: 'JSTreeContainer',
        tagHolder: ['JSTree'],
        messageHandler: ['JSMessages'],
        location: ''
      };
      onSave = false;
      dataSettings = {
        pullSets: [291, 296, 292],
        entity_id: 0
      };
      displaySettings = {
        defaultTree: 291,
        mode: 'edit',
        size: 'full',
        autocomplete: true,
        print: true,
        showActive: true,
        showStubs: false
      };
      callAjax = {
        url: 'localtagdata.json',
        dataType: 'json'
      };
      this.get = function(name) {
        var getRet;
        getRet = {};
        if ('pageElements' === name) {
          cj.extend(true, getRet, pageElements);
        }
        if ('onSave' === name) {
          return onSave;
        }
        if ('dataSettings' === name) {
          cj.extend(true, getRet, dataSettings);
        }
        if ('displaySettings' === name) {
          cj.extend(true, getRet, displaySettings);
        }
        if ('callAjax' === name) {
          cj.extend(true, getRet, callAjax);
        }
        if ('ready' === name) {
          return ready;
        }
        return getRet;
      };
      this.set = function(name, obj) {
        var ready;
        if ('pageElements' === name) {
          obj = _utils.checkForArray(pageElements, obj);
          cj.extend(true, pageElements, obj);
        }
        if ('onSave' === name) {
          onSave = obj;
        }
        if ('dataSettings' === name) {
          obj = _utils.checkForArray(dataSettings, obj);
          cj.extend(true, dataSettings, obj);
        }
        if ('displaySettings' === name) {
          obj = _utils.checkForArray(displaySettings, obj);
          cj.extend(true, displaySettings, obj);
        }
        if ('callAjax' === name) {
          obj = _utils.checkForArray(callAjax, obj);
          cj.extend(true, callAjax, obj);
        }
        if ('ready' === name) {
          return ready = obj;
        }
      };
    }

    Instance.property("rawData", {
      get: function() {
        return this._rawData;
      },
      set: function(a) {
        return this._rawData = a;
      }
    });

    Instance.property("autocomplete", {
      get: function() {
        return this._autocomplete;
      },
      set: function(a) {
        return this._autocomplete = a;
      }
    });

    Instance.property("treeNames", {
      get: function() {
        return this._treeNames;
      },
      set: function(a) {
        return this._treeNames = a;
      }
    });

    Instance.property("trees", {
      get: function() {
        return this._trees;
      },
      set: function(a) {
        return this._trees = a;
      }
    });

    return Instance;

  })();

  _utils = {
    removeDupFromExtend: function(obj) {
      return cj.each(obj, function(k, v) {
        if (cj.isPlainObject(v)) {
          _this.removeDupFromExtend(v);
        }
        return v = bbUtils.uniqueAry(v);
      });
    },
    checkForArray: function(propDefault, obj) {
      return cj.each(obj, function(k, def) {
        var a, ar, b, c, i, _i, _j, _len, _len1;
        if (cj.isArray(def) && cj.isArray(propDefault[k])) {
          a = propDefault[k].sort();
          b = def.sort();
          for (i = _i = 0, _len = a.length; _i < _len; i = ++_i) {
            c = a[i];
            if (c !== b[i]) {
              for (_j = 0, _len1 = def.length; _j < _len1; _j++) {
                ar = def[_j];
                if (propDefault[k].indexOf(ar) < 0) {
                  propDefault[k].push(ar);
                }
              }
            }
          }
          return obj[k] = propDefault[k];
        }
      });
    },
    textWrap: function(text, length) {
      var a, numberOfSegs, rx, seg, shouldRet, toRet, _i;
      numberOfSegs = Math.ceil(text.length / length);
      toRet = "";
      shouldRet = false;
      rx = /\s|-| |\u00A0|\u8209|\r|\n/g;
      for (a = _i = 0; 0 <= numberOfSegs ? _i <= numberOfSegs : _i >= numberOfSegs; a = 0 <= numberOfSegs ? ++_i : --_i) {
        seg = text.slice(length * a, length * (a + 1));
        if (!seg.match(rx) && seg.length >= length) {
          shouldRet = true;
          toRet += "" + seg + " ";
        } else {
          toRet += "" + seg;
        }
      }
      if (shouldRet) {
        return toRet;
      }
      return text;
    }
  };

  window.jstree = jstree;

  Tree = (function() {
    function Tree() {}

    return Tree;

  })();

  Node = (function() {
    function Node() {}

    return Node;

  })();

  window.jstree["views"] = {
    exec: function(params) {
      console.log("exec");
      return this.view = new View(params);
    },
    done: function(params) {
      return console.log("done");
    }
  };

  View = (function() {
    function View(instance) {
      this.instance = instance;
      this.writeContainers();
    }

    View.prototype.writeContainers = function() {
      console.log(this.instance);
      this.formatPageElements();
      return this.addClassesToElement();
    };

    View.prototype.addClassesToElement = function() {
      this.cjInitHolderId.html("<div class='" + this.addClassHolderString + "'></div>");
      this.cjInitHolderId.prepend(this.menuHtml(this.menuName));
      this.cjInitHolderId.append(this.dataHolderHtml);
      this.cjInitHolderId.append(this.tokenHolderHtml(this.tokenHolder));
      return this.cjInitHolderId.removeClass(this.initHolderId).attr("id", this.addIdWrapperString);
    };

    View.prototype.formatPageElements = function() {
      var displayElements, i, pageElements, selector, _i, _len, _ref, _ref1;
      pageElements = this.instance.get('pageElements');
      displayElements = this.instance.get('displaySettings');
      _ref = ["", ""], this.tagHolderSelector = _ref[0], this.tagWrapperSelector = _ref[1];
      this.menuName = {
        menu: "",
        top: "",
        tabs: "",
        bottom: "",
        autocomplete: "",
        settings: ""
      };
      this.tokenHolder = {
        tokenHolder: "",
        options: "",
        body: "",
        resize: "",
        left: ""
      };
      this.addIdWrapperString = pageElements.wrapper;
      this.addBoxSizing = pageElements.size;
      this.addClassHolderString = pageElements.tagHolder;
      this.initHolderId = pageElements.init;
      this.cjInitHolderId = cj("." + this.initHolderId);
      this.addClassHolderString = this.ifisarrayjoin(this.addClassHolderString);
      _ref1 = pageElements.tagHolder;
      for (i = _i = 0, _len = _ref1.length; _i < _len; i = ++_i) {
        selector = _ref1[i];
        selector = selector.replace(" ", "-");
        this.menuName = this.concatOnObj(this.menuName, selector);
        this.tokenHolder = this.concatOnObj(this.tokenHolder, selector);
        this.tagHolderSelector = this.tagHolderSelector.concat("." + selector);
      }
      return this.tagWrapperSelector = this.tagWrapperSelector.concat("#" + pageElements.wrapper);
    };

    View.prototype.separateSizeElements = function(el) {
      var a, b, classNames, _i, _len;
      el.replace(/\./, "");
      el.replace(/#/, "");
      classNames = el.split(" ");
      for (b = _i = 0, _len = classNames.length; _i < _len; b = ++_i) {
        a = classNames[b];
        el += "." + b;
      }
      return el;
    };

    View.prototype.ifisarrayjoin = function(toJoin) {
      if (cj.isArray(toJoin)) {
        return toJoin = toJoin.join(" ");
      }
    };

    View.prototype.concatOnObj = function(obj, selector, classOrId) {
      var k, v;
      if (classOrId == null) {
        classOrId = ".";
      }
      for (k in obj) {
        v = obj[k];
        if (k.substr(0, 3) === "cj_") {
          break;
        }
        if (typeof obj["cj_" + k] === "undefined") {
          obj["cj_" + k] = "";
        }
        obj["cj_" + k] = obj["cj_" + k].concat("" + classOrId + selector + "-" + k);
        obj[k] = obj[k].concat("" + selector + "-" + k + " ");
      }
      return obj;
    };

    View.prototype.getCJQsaves = function() {
      this.cjTagWrapperSelector = cj(this.tagWrapperSelector);
      this.cjTagHolderSelector = cj(this.tagHolderSelector);
      this.cjInstanceSelector = cj(this.tagWrapperSelector.concat(" " + this.tagHolderSelector));
      return this.cjTabs = cj(this.menuName.cj_tabs);
    };

    View.prototype.menuHtml = function(name) {
      return "      <div class='" + name.menu + "'>       <div class='" + name.top + "'>        <div class='" + name.tabs + "'></div>        <div class='" + name.settings + "'></div>       </div>       <div class='" + name.bottom + "'>        <div class='" + name.autocomplete + "'>         <input type='text' id='JSTree-ac'>        </div>        <div class='" + name.settings + "'></div>       </div>      </div>    ";
    };

    View.prototype.tokenHolderHtml = function(name) {
      return "        <div class='" + name.tokenHolder + "'>         <div class='" + name.resize + "'></div>         <div class='" + name.body + "'>          <div class='" + name.left + "'></div>          <div class='" + name.options + "'></div>         </div>        </div>      ";
    };

    View.prototype.dataHolderHtml = function() {
      return "<div id='JSTree-data' style='display:none'></div>";
    };

    return View;

  })();

}).call(this);
