<?php

/**
 * @file
 * Cache Router module helper.
 *
 * @author Steve Rude <steve@slantview.com>
 */

/**
 * Implementation of hook_user().
 *
 * When logged in you don't want to hit the page_fast_cache or else you will serve
 * a cached page to a logged in user.
 */
function cacherouter_user($op, &$edit, &$account, $category = NULL) {
  switch ($op) {
    case 'login':
      $params = session_get_cookie_params();
      $cookie_name = variable_get('cacherouter_cookie', 'DRUPAL_UID');
      if (version_compare(PHP_VERSION, '5.2.0') >= 0) {
        setcookie($cookie_name, TRUE, $_SERVER['REQUEST_TIME'] + (60 * 60 * 24 * 30), $params['path'], $params['domain'], $params['secure'], $params['httponly']);
      }
      else {
        setcookie($cookie_name, TRUE, $_SERVER['REQUEST_TIME'] + (60 * 60 * 24 * 30), $params['path'], $params['domain'], $params['secure']);
      }
      break;

    case 'logout':
      $params = session_get_cookie_params();
      $cookie_name = variable_get('cacherouter_cookie', 'DRUPAL_UID');
      // Set in past to delete cookie
      if (version_compare(PHP_VERSION, '5.2.0') >= 0) {
        setcookie($cookie_name, TRUE, $_SERVER['REQUEST_TIME'] - 3600, $params['path'], $params['domain'], $params['secure'], $params['httponly']);
      }
      else {
        setcookie($cookie_name, TRUE, $_SERVER['REQUEST_TIME'] - 3600, $params['path'], $params['domain'], $params['secure']);
      }
      unset($_COOKIE[$cookie_name]);
      break;
  }
}
