<?php
use CRM_NYSS_CaseloadDash_ExtensionUtil as E;

return [
  [
    'name' => 'SavedSearch_NYSS_Caseload_Manager_Details',
    'entity' => 'SavedSearch',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'NYSS_Caseload_Manager_Details',
        'label' => E::ts('NYSS Caseload - Case Manager Details'),
        'api_entity' => 'Case',
        'api_params' => [
          'version' => 4,
          'checkPermissions' => FALSE,
          'select' => [
            'id',
            'subject',
            'case_type_id:label',
            'status_id:label',
            'start_date',
            'end_date',
            'GROUP_CONCAT(DISTINCT Case_CaseContact_Contact_01.sort_name) AS GROUP_CONCAT_Case_CaseContact_Contact_01_sort_name',
            'segment_NYSS_Caseload_Open:label',
            'segment_NYSS_Caseload_Urgent:label',
            'segment_NYSS_Caseload_Resolved:label',
            'segment_NYSS_Caseload_Newer_Than_7_Days:label',
            'segment_NYSS_Caseload_7_To_30_Days:label',
            'segment_NYSS_Caseload_Older_Than_30_Days:label',
            'segment_NYSS_Caseload_Resolved_Last_7_Days:label',
            'DATEDIFF(end_date, start_date) AS DATEDIFF_end_date_start_date',
            'Case_CaseContact_Contact_01_Contact_RelationshipCache_Case_01.near_contact_id',
            'Case_CaseContact_Contact_01_Contact_RelationshipCache_Case_01.near_contact_id.display_name',
          ],
          'orderBy' => [],
          'where' => [
            ['is_deleted', '=', FALSE],
            [
              'OR',
              [
                [
                  'segment_NYSS_Caseload_Resolved',
                  'IS EMPTY',
                ],
                [
                  'AND',
                  [
                    [
                      'segment_NYSS_Caseload_Resolved',
                      '=',
                      '1',
                    ],
                    ['end_date', '>', 'now - 90 day'],
                  ],
                ],
              ],
            ],
          ],
          'groupBy' => [
            'Case_CaseContact_Contact_01_Contact_RelationshipCache_Case_01.near_contact_id',
            'Case_CaseContact_Contact_01_Contact_RelationshipCache_Case_01.near_contact_id.sort_name',
            'id',
          ],
          'join' => [
            [
              'Contact AS Case_CaseContact_Contact_01',
              'LEFT',
              'CaseContact',
              [
                'id',
                '=',
                'Case_CaseContact_Contact_01.case_id',
              ],
            ],
            [
              'Case AS Case_CaseContact_Contact_01_Contact_RelationshipCache_Case_01',
              'INNER',
              'RelationshipCache',
              [
                'Case_CaseContact_Contact_01.id',
                '=',
                'Case_CaseContact_Contact_01_Contact_RelationshipCache_Case_01.far_contact_id',
              ],
              [
                'Case_CaseContact_Contact_01_Contact_RelationshipCache_Case_01.near_relation:name',
                '=',
                '"Case Manager"',
              ],
              [
                'Case_CaseContact_Contact_01_Contact_RelationshipCache_Case_01.is_current',
                '=',
                TRUE,
              ],
              [
                'Case_CaseContact_Contact_01_Contact_RelationshipCache_Case_01.id',
                '=',
                'id',
              ],
            ],
          ],
          'having' => [],
        ],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'SavedSearch_NYSS_Caseload_Manager_Details_SearchDisplay_Case_Manager_Cases_Details_Table',
    'entity' => 'SearchDisplay',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Case_Manager_Cases_Details_Table',
        'label' => E::ts('Case Manager Cases Details'),
        'saved_search_id.name' => 'NYSS_Caseload_Manager_Details',
        'type' => 'table',
        'settings' => [
          'description' => E::ts(''),
          'sort' => [],
          'limit' => 10,
          'pager' => [],
          'placeholder' => 5,
          'columns' => [
            [
              'type' => 'html',
              'key' => 'id',
              'label' => E::ts('Case'),
              'sortable' => TRUE,
              'rewrite' => '<a href="/civicrm/contact/view/case?id=[id]&action=view&context=case&reset=1" target="_blank">#[id] &mdash; [subject]</a>',
            ],
            [
              'type' => 'field',
              'key' => 'GROUP_CONCAT_Case_CaseContact_Contact_01_sort_name',
              'label' => E::ts('Constituent(s)'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'case_type_id:label',
              'label' => E::ts('Case Type'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'status_id:label',
              'label' => E::ts('Status'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'start_date',
              'label' => E::ts('Start Date'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'Case_CaseContact_Contact_01_Contact_RelationshipCache_Case_01.near_contact_id.display_name',
              'label' => E::ts('Case Manager'),
              'sortable' => TRUE,
            ],
          ],
          'actions' => TRUE,
          'classes' => ['table', 'table-striped'],
          'actions_display_mode' => 'menu',
          'headerCount' => TRUE,
        ],
      ],
      'match' => [
        'saved_search_id',
        'name',
      ],
    ],
  ],
  [
    'name' => 'SavedSearch_NYSS_Caseload_Manager_Details_SearchDisplay_NyssCaseloadManagerDetailsStats',
    'entity' => 'SearchDisplay',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'NyssCaseloadManagerDetailsStats',
        'label' => E::ts('NYSS Caseload - Case Manager Details Stats DB View'),
        'saved_search_id.name' => 'NYSS_Caseload_Manager_Details',
        'type' => 'entity',
        'settings' => [
          'sort' => [],
          'columns' => [
            [
              'type' => 'field',
              'key' => 'Case_CaseContact_Contact_01_Contact_RelationshipCache_Case_01.near_contact_id',
              'label' => E::ts('Case Manager ID'),
              'spec' => [
                'name' => 'Case_CaseContact_Contact_01_Contact_Relaticd0b67c6898a0668',
                'data_type' => 'Integer',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'near_contact_id',
                'original_field_entity' => 'RelationshipCache',
                'input_type' => 'EntityRef',
                'entity_reference' => [
                  'entity' => 'Contact',
                  'key' => 'id',
                  'on_delete' => 'CASCADE',
                ],
              ],
            ],
            [
              'type' => 'field',
              'key' => 'Case_CaseContact_Contact_01_Contact_RelationshipCache_Case_01.near_contact_id.display_name',
              'label' => E::ts('Case Manager Display Name'),
              'spec' => [
                'name' => 'Case_CaseContact_Contact_01_Contact_Relati55de3f513091bdce',
                'data_type' => 'String',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'display_name',
                'original_field_entity' => 'Contact',
                'input_type' => 'Text',
                'entity_reference' => NULL,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'id',
              'label' => E::ts('Case ID'),
              'spec' => [
                'name' => 'id',
                'data_type' => 'Integer',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'id',
                'original_field_entity' => 'Case',
                'entity_reference' => [
                  'entity' => 'Case',
                ],
                'input_type' => 'EntityRef',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'segment_NYSS_Caseload_Open:label',
              'label' => E::ts('Open'),
              'spec' => [
                'name' => 'segment_NYSS_Caseload_Open',
                'data_type' => 'String',
                'suffixes' => ['id', 'label'],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'segment_NYSS_Caseload_Open',
                'original_field_entity' => 'Case',
                'input_type' => NULL,
                'entity_reference' => NULL,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'segment_NYSS_Caseload_Urgent:label',
              'label' => E::ts('Urgent'),
              'spec' => [
                'name' => 'segment_NYSS_Caseload_Urgent',
                'data_type' => 'String',
                'suffixes' => ['id', 'label'],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'segment_NYSS_Caseload_Urgent',
                'original_field_entity' => 'Case',
                'input_type' => NULL,
                'entity_reference' => NULL,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'segment_NYSS_Caseload_Resolved:label',
              'label' => E::ts('Resolved'),
              'spec' => [
                'name' => 'segment_NYSS_Caseload_Resolved',
                'data_type' => 'String',
                'suffixes' => ['id', 'label'],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'segment_NYSS_Caseload_Resolved',
                'original_field_entity' => 'Case',
                'input_type' => NULL,
                'entity_reference' => NULL,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'segment_NYSS_Caseload_Newer_Than_7_Days:label',
              'label' => E::ts('Open < 7 Days'),
              'spec' => [
                'name' => 'segment_NYSS_Caseload_Newer_Than_7_Days',
                'data_type' => 'String',
                'suffixes' => ['id', 'label'],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'segment_NYSS_Caseload_Newer_Than_7_Days',
                'original_field_entity' => 'Case',
                'input_type' => NULL,
                'entity_reference' => NULL,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'segment_NYSS_Caseload_7_To_30_Days:label',
              'label' => E::ts('Open 7 - 30 Days'),
              'spec' => [
                'name' => 'segment_NYSS_Caseload_7_To_30_Days',
                'data_type' => 'String',
                'suffixes' => ['id', 'label'],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'segment_NYSS_Caseload_7_To_30_Days',
                'original_field_entity' => 'Case',
                'input_type' => NULL,
                'entity_reference' => NULL,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'segment_NYSS_Caseload_Older_Than_30_Days:label',
              'label' => E::ts('Open > 30 Days'),
              'spec' => [
                'name' => 'segment_NYSS_Caseload_Older_Than_30_Days',
                'data_type' => 'String',
                'suffixes' => ['id', 'label'],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'segment_NYSS_Caseload_Older_Than_30_Days',
                'original_field_entity' => 'Case',
                'input_type' => NULL,
                'entity_reference' => NULL,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'segment_NYSS_Caseload_Resolved_Last_7_Days:label',
              'label' => E::ts('Resolved Last 7 Days'),
              'spec' => [
                'name' => 'segment_NYSS_Caseload_Resolved_Last_7_Days',
                'data_type' => 'String',
                'suffixes' => ['id', 'label'],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'segment_NYSS_Caseload_Resolved_Last_7_Days',
                'original_field_entity' => 'Case',
                'input_type' => NULL,
                'entity_reference' => NULL,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'DATEDIFF_end_date_start_date',
              'label' => E::ts('Time to Resolution'),
              'spec' => [
                'name' => 'DATEDIFF_end_date_start_date',
                'data_type' => 'Integer',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'end_date',
                'original_field_entity' => 'Case',
                'input_type' => 'Number',
              ],
            ],
          ],
          'data_mode' => 'view',
        ],
      ],
      'match' => [
        'saved_search_id',
        'name',
      ],
    ],
  ],
];
