<?php
use CRM_NYSS_CaseloadDash_ExtensionUtil as E;

return [
  [
    'name' => 'SavedSearch_NYSS_Caseload_Manager_Totals',
    'entity' => 'SavedSearch',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'NYSS_Caseload_Manager_Totals',
        'label' => E::ts('NYSS Caseload - Case Manager Totals'),
        'api_entity' => 'SK_NyssCaseloadManagerDetailsStats',
        'api_params' => [
          'version' => 4,
          'select' => [
            'Case_CaseContact_Contact_01_Contact_Relaticd0b67c6898a0668',
            'Case_CaseContact_Contact_01_Contact_Relati0e9a026673a1bc81',
            'COUNT(segment_NYSS_Caseload_Open) AS COUNT_segment_NYSS_Caseload_Open',
            'COUNT(segment_NYSS_Caseload_Urgent) AS COUNT_segment_NYSS_Caseload_Urgent',
            'COUNT(segment_NYSS_Caseload_Newer_Than_7_Days) AS COUNT_segment_NYSS_Caseload_Newer_Than_7_Days',
            'COUNT(segment_NYSS_Caseload_7_To_30_Days) AS COUNT_segment_NYSS_Caseload_7_To_30_Days',
            'COUNT(segment_NYSS_Caseload_Older_Than_30_Days) AS COUNT_segment_NYSS_Caseload_Older_Than_30_Days',
            'COUNT(segment_NYSS_Caseload_Resolved_Last_7_Days) AS COUNT_segment_NYSS_Caseload_Resolved_Last_7_Days',
            'AVG(DATEDIFF_end_date_start_date) AS AVG_DATEDIFF_end_date_start_date',
          ],
          'orderBy' => [],
          'where' => [],
          'groupBy' => [
            'Case_CaseContact_Contact_01_Contact_Relaticd0b67c6898a0668',
            'Case_CaseContact_Contact_01_Contact_Relati0e9a026673a1bc81',
          ],
          'join' => [],
          'having' => [],
        ],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'SavedSearch_NYSS_Caseload_Manager_Totals_SearchDisplay_Case_Manager_Totals_Chart_Older_Than_30_Days',
    'entity' => 'SearchDisplay',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Case_Manager_Totals_Chart_Older_Than_30_Days',
        'label' => E::ts('Case Manager Totals - Aging Cases Chart'),
        'saved_search_id.name' => 'NYSS_Caseload_Manager_Totals',
        'type' => 'chart-kit',
        'settings' => [
          'columns' => [
            [
              'axis' => 'w',
              'key' => 'Case_CaseContact_Contact_01_Contact_Relati0e9a026673a1bc81',
              'index' => 0,
              'name' => 'w_0',
              'label' => E::ts('Case Manager'),
              'sourceDataType' => 'String',
              'scaleType' => 'categorical',
              'datePrecision' => NULL,
              'reduceType' => 'list',
              'seriesType' => NULL,
              'dataLabelType' => 'label',
              'dataLabelFormatter' => 'none',
              'isDimension' => TRUE,
              'isOrder' => FALSE,
            ],
            [
              'axis' => 'y',
              'key' => 'COUNT_segment_NYSS_Caseload_Older_Than_30_Days',
              'index' => 1,
              'name' => 'y_0',
              'label' => E::ts('(Count) Open > 30 Days'),
              'sourceDataType' => 'Integer',
              'scaleType' => 'numeric',
              'datePrecision' => NULL,
              'reduceType' => 'sum',
              'seriesType' => NULL,
              'dataLabelType' => 'label',
              'dataLabelFormatter' => 'none',
              'isDimension' => FALSE,
              'isOrder' => TRUE,
            ],
          ],
          'format' => [
            'labelColor' => '#ffffff',
            'backgroundColor' => '#000000',
            'height' => 480,
            'width' => 700,
            'padding' => [
              'outer' => 10,
              'clip' => 20,
              'top' => 50,
              'bottom' => 50,
              'left' => 50,
              'right' => 50,
            ],
            'title' => E::ts('Cases Older Than 30 Days'),
          ],
          'maxSegments' => 5,
          'chartOrderColIndex' => 0,
          'chartOrderDir' => 'DESC',
          'chartType' => 'row',
          'sort' => [
            [
              'Case_CaseContact_Contact_01_Contact_Relati0e9a026673a1bc81',
              'ASC',
            ],
          ],
        ],
      ],
      'match' => [
        'saved_search_id',
        'name',
      ],
    ],
  ],
  [
    'name' => 'SavedSearch_NYSS_Caseload_Manager_Totals_SearchDisplay_Case_Manager_Totals_Chart_Open_Cases',
    'entity' => 'SearchDisplay',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Case_Manager_Totals_Chart_Open_Cases',
        'label' => E::ts('Case Manager Totals - Open Cases Chart'),
        'saved_search_id.name' => 'NYSS_Caseload_Manager_Totals',
        'type' => 'chart-kit',
        'settings' => [
          'columns' => [
            [
              'axis' => 'w',
              'key' => 'Case_CaseContact_Contact_01_Contact_Relati0e9a026673a1bc81',
              'index' => 0,
              'name' => 'w_0',
              'label' => E::ts('Case Manager'),
              'sourceDataType' => 'String',
              'scaleType' => 'categorical',
              'datePrecision' => NULL,
              'reduceType' => 'list',
              'seriesType' => NULL,
              'dataLabelType' => 'label',
              'dataLabelFormatter' => 'none',
              'isDimension' => TRUE,
              'dataLabelColumnPrefix' => FALSE,
              'isOrder' => FALSE,
            ],
            [
              'axis' => 'y',
              'key' => 'COUNT_segment_NYSS_Caseload_Open',
              'index' => 1,
              'name' => 'y_0',
              'label' => E::ts('(Count) Open'),
              'sourceDataType' => 'Integer',
              'scaleType' => 'numeric',
              'datePrecision' => NULL,
              'reduceType' => 'sum',
              'seriesType' => NULL,
              'dataLabelType' => 'label',
              'dataLabelFormatter' => 'none',
              'isDimension' => FALSE,
              'isOrder' => TRUE,
            ],
          ],
          'format' => [
            'labelColor' => '#ffffff',
            'backgroundColor' => '#000000',
            'height' => 480,
            'width' => 700,
            'padding' => [
              'outer' => 10,
              'clip' => 20,
              'top' => 50,
              'bottom' => 50,
              'left' => 50,
              'right' => 50,
            ],
            'title' => E::ts('Most Open Cases'),
          ],
          'maxSegments' => 5,
          'chartOrderColIndex' => 0,
          'chartOrderDir' => 'DESC',
          'chartType' => 'row',
          'sort' => [
            [
              'Case_CaseContact_Contact_01_Contact_Relati0e9a026673a1bc81',
              'ASC',
            ],
          ],
        ],
      ],
      'match' => [
        'saved_search_id',
        'name',
      ],
    ],
  ],
  [
    'name' => 'SavedSearch_NYSS_Caseload_Manager_Totals_SearchDisplay_Case_Manager_Totals_Chart_Resolution_Rate',
    'entity' => 'SearchDisplay',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Case_Manager_Totals_Chart_Resolution_Rate',
        'label' => E::ts('Case Manager Totals - Resolution Rate Chart'),
        'saved_search_id.name' => 'NYSS_Caseload_Manager_Totals',
        'type' => 'chart-kit',
        'settings' => [
          'columns' => [
            [
              'axis' => 'w',
              'key' => 'Case_CaseContact_Contact_01_Contact_Relati0e9a026673a1bc81',
              'index' => 0,
              'name' => 'w_0',
              'label' => E::ts('Case Manager'),
              'sourceDataType' => 'String',
              'scaleType' => 'categorical',
              'datePrecision' => NULL,
              'reduceType' => 'list',
              'seriesType' => NULL,
              'dataLabelType' => 'label',
              'dataLabelFormatter' => 'none',
              'isDimension' => TRUE,
              'isOrder' => FALSE,
            ],
            [
              'axis' => 'y',
              'key' => 'AVG_DATEDIFF_end_date_start_date',
              'index' => 1,
              'name' => 'y_0',
              'label' => E::ts('Avg. Days to Resolution'),
              'sourceDataType' => 'Float',
              'scaleType' => 'numeric',
              'datePrecision' => NULL,
              'reduceType' => 'mean',
              'seriesType' => NULL,
              'dataLabelType' => 'label',
              'dataLabelFormatter' => 'none',
              'isDimension' => FALSE,
              'isOrder' => TRUE,
            ],
          ],
          'format' => [
            'labelColor' => '#ffffff',
            'backgroundColor' => '#000000',
            'height' => 480,
            'width' => 700,
            'padding' => [
              'outer' => 10,
              'clip' => 20,
              'top' => 50,
              'bottom' => 50,
              'left' => 50,
              'right' => 50,
            ],
            'title' => E::ts('Resolution Rate (Days)'),
          ],
          'maxSegments' => 5,
          'chartOrderColIndex' => 0,
          'chartOrderDir' => 'DESC',
          'chartType' => 'row',
          'sort' => [
            [
              'Case_CaseContact_Contact_01_Contact_Relati0e9a026673a1bc81',
              'ASC',
            ],
          ],
        ],
      ],
      'match' => [
        'saved_search_id',
        'name',
      ],
    ],
  ],
  [
    'name' => 'SavedSearch_NYSS_Caseload_Manager_Totals_SearchDisplay_Case_Manager_Totals_Table',
    'entity' => 'SearchDisplay',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Case_Manager_Totals_Table',
        'label' => E::ts('Case Manager Totals Table'),
        'saved_search_id.name' => 'NYSS_Caseload_Manager_Totals',
        'type' => 'table',
        'settings' => [
          'description' => E::ts(''),
          'sort' => [
            [
              'COUNT_segment_NYSS_Caseload_Open',
              'DESC',
            ],
          ],
          'limit' => 5,
          'pager' => [],
          'placeholder' => 5,
          'columns' => [
            [
              'type' => 'field',
              'key' => 'Case_CaseContact_Contact_01_Contact_Relati0e9a026673a1bc81',
              'label' => E::ts('Case Manager'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'html',
              'key' => 'COUNT_segment_NYSS_Caseload_Open',
              'label' => E::ts('Open Cases'),
              'sortable' => TRUE,
              'alignment' => 'text-center',
              'rewrite' => "<a class=\"crm-popup\" href=\"/civicrm/nyss/caseload/case-manager#?Case_Manager=[Case_CaseContact_Contact_01_Contact_Relaticd0b67c6898a0668]&Case_Manager_Open=true&popup_title=[Case_CaseContact_Contact_01_Contact_Relati0e9a026673a1bc81]%20%E2%80%94%20Open%20Cases\">[COUNT_segment_NYSS_Caseload_Open]</a>",
            ],
            [
              'type' => 'html',
              'key' => 'COUNT_segment_NYSS_Caseload_Urgent',
              'label' => E::ts('Urgent Cases'),
              'sortable' => TRUE,
              'alignment' => 'text-center',
              'rewrite' => "<a class=\"crm-popup\" href=\"/civicrm/nyss/caseload/case-manager#?Case_Manager=[Case_CaseContact_Contact_01_Contact_Relaticd0b67c6898a0668]&Case_Manager_Urgent=true&popup_title=[Case_CaseContact_Contact_01_Contact_Relati0e9a026673a1bc81]%20%E2%80%94%20Urgent%20Cases\">[COUNT_segment_NYSS_Caseload_Urgent]</a>",
            ],
            [
              'type' => 'html',
              'key' => 'COUNT_segment_NYSS_Caseload_Newer_Than_7_Days',
              'label' => E::ts('Open < 7 Days'),
              'sortable' => TRUE,
              'alignment' => 'text-center',
              'rewrite' => "<a class=\"crm-popup\" href=\"/civicrm/nyss/caseload/case-manager#?Case_Manager=[Case_CaseContact_Contact_01_Contact_Relaticd0b67c6898a0668]&Case_Manager_Newer_Than_7_Days=true&popup_title=[Case_CaseContact_Contact_01_Contact_Relati0e9a026673a1bc81]%20%E2%80%94%20Open+%2F+7+Days\">[COUNT_segment_NYSS_Caseload_Newer_Than_7_Days]</a>",
            ],
            [
              'type' => 'html',
              'key' => 'COUNT_segment_NYSS_Caseload_7_To_30_Days',
              'label' => E::ts('Open 7 - 30 Days'),
              'sortable' => TRUE,
              'alignment' => 'text-center',
              'rewrite' => "<a class=\"crm-popup\" href=\"/civicrm/nyss/caseload/case-manager#?Case_Manager=[Case_CaseContact_Contact_01_Contact_Relaticd0b67c6898a0668]&Case_Manager_7_To_30_Days=true&popup_title=[Case_CaseContact_Contact_01_Contact_Relati0e9a026673a1bc81]%20%E2%80%94%20Open+7+%2D+30+Days\">[COUNT_segment_NYSS_Caseload_7_To_30_Days]</a>",
            ],
            [
              'type' => 'html',
              'key' => 'COUNT_segment_NYSS_Caseload_Older_Than_30_Days',
              'label' => E::ts('Open > 30 Days'),
              'sortable' => TRUE,
              'alignment' => 'text-center',
              'rewrite' => "<a class=\"crm-popup\" href=\"/civicrm/nyss/caseload/case-manager#?Case_Manager=[Case_CaseContact_Contact_01_Contact_Relaticd0b67c6898a0668]&Case_Manager_Older_Than_30_Days=true&popup_title=[Case_CaseContact_Contact_01_Contact_Relati0e9a026673a1bc81]%20%E2%80%94%20Open+%3E+Than+30+Days\">[COUNT_segment_NYSS_Caseload_Older_Than_30_Days]</a>",
            ],
            [
              'type' => 'html',
              'key' => 'COUNT_segment_NYSS_Caseload_Resolved_Last_7_Days',
              'label' => E::ts('Resolved Last 7 Days'),
              'sortable' => TRUE,
              'alignment' => 'text-center',
              'rewrite' => "<a class=\"crm-popup\" href=\"/civicrm/nyss/caseload/case-manager#?Case_Manager=[Case_CaseContact_Contact_01_Contact_Relaticd0b67c6898a0668]&Case_Manager_Resolved_Last_7_Days=true&popup_title=[Case_CaseContact_Contact_01_Contact_Relati0e9a026673a1bc81]%20%E2%80%94%20Resolved+Last+7+Days\">[COUNT_segment_NYSS_Caseload_Resolved_Last_7_Days]</a>",
            ],
            [
              'type' => 'field',
              'key' => 'AVG_DATEDIFF_end_date_start_date',
              'label' => E::ts('Avg. Days to Resolution'),
              'sortable' => TRUE,
              'alignment' => 'text-center',
            ],
          ],
          'actions' => TRUE,
          'classes' => ['table', 'table-striped'],
          'actions_display_mode' => 'menu',
          //'headerCount' => TRUE,
        ],
      ],
      'match' => [
        'saved_search_id',
        'name',
      ],
    ],
  ],
];
