<?php
use CRM_NYSS_CaseloadDash_ExtensionUtil as E;

return [
  [
    'name' => 'SavedSearch_NYSS_Caseload_Overview_Details',
    'entity' => 'SavedSearch',
    'cleanup' => 'unused',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'NYSS_Caseload_Overview_Details',
        'label' => E::ts('NYSS Caseload - Overview Details'),
        'api_entity' => 'Case',
        'api_params' => [
          'version' => 4,
          'checkPermissions' => FALSE,
          'select' => [
            'id',
            'subject',
            'case_type_id:label',
            'status_id:label',
            'start_date',
            'end_date',
            'segment_NYSS_Caseload_Open:label',
            'segment_NYSS_Caseload_Resolved:label',
            'Case_SK_NyssCaseloadUnassignedCases_id_01.segment_NYSS_Caseload_Unassigned:label',
            'Case_SK_NyssCaseloadUnassignedCases_id_01.segment_NYSS_Caseload_Unassigned',
            'segment_NYSS_Caseload_Urgent:label',
            'segment_NYSS_Caseload_Newer_Than_7_Days:label',
            'segment_NYSS_Caseload_Older_Than_7_Days:label',
            'segment_NYSS_Caseload_7_To_30_Days:label',
            'segment_NYSS_Caseload_Older_Than_30_Days:label',
            'segment_NYSS_Caseload_Resolved_Last_7_Days:label',
            'IF(ISNOTNULL(segment_NYSS_Caseload_Opened_Within_180_Days), DATEDIFF(end_date, start_date), NULL) AS DATEDIFF_end_date_start_date',
            'SUM(Case_SK_NyssCaseloadUnassignedCases_id_01.COUNT_Case_CaseContact_Contact_01_Contact_a6c385c12bd86d07) AS SUM_Case_SK_NyssCaseloadUnassignedCases_id_01_COUNT_Case_CaseContact_Contact_01_Contact_a6c385c12bd86d07',
            'GROUP_CONCAT(DISTINCT Case_CaseContact_Contact_01.sort_name) AS GROUP_CONCAT_Case_CaseContact_Contact_01_sort_name',
            'GROUP_CONCAT(DISTINCT Case_CaseContact_Contact_01_Contact_RelationshipCache_Case_01.near_contact_id.display_name) AS GROUP_CONCAT_Case_CaseContact_Contact_01_Contact_RelationshipCache_Case_01_near_contact_id_display_name',
          ],
          'orderBy' => [],
          'where' => [
            ['is_deleted', '=', FALSE],
            [
              'OR',
              [
                ['status_id:name', '!=', 'Closed'],
                [
                  'AND',
                  [
                    ['status_id:name', '=', 'Closed'],
                    ['end_date', '>', 'now - 180 day'],
                  ],
                ],
              ],
            ],
          ],
          'groupBy' => [
            'id',
            'subject',
            'case_type_id',
            'start_date',
            'end_date',
            'status_id',
          ],
          'join' => [
            [
              'SK_NyssCaseloadUnassignedCases AS Case_SK_NyssCaseloadUnassignedCases_id_01',
              'LEFT',
              [
                'id',
                '=',
                'Case_SK_NyssCaseloadUnassignedCases_id_01.id',
              ],
            ],
            [
              'Contact AS Case_CaseContact_Contact_01',
              'LEFT',
              'CaseContact',
              [
                'id',
                '=',
                'Case_CaseContact_Contact_01.case_id',
              ],
            ],
            [
              'Case AS Case_CaseContact_Contact_01_Contact_RelationshipCache_Case_01',
              'LEFT',
              'RelationshipCache',
              [
                'Case_CaseContact_Contact_01.id',
                '=',
                'Case_CaseContact_Contact_01_Contact_RelationshipCache_Case_01.far_contact_id',
              ],
              [
                'Case_CaseContact_Contact_01_Contact_RelationshipCache_Case_01.near_relation:name',
                '=',
                '"Case Manager"',
              ],
              [
                'Case_CaseContact_Contact_01_Contact_RelationshipCache_Case_01.is_current',
                '=',
                TRUE,
              ],
              [
                'Case_CaseContact_Contact_01_Contact_RelationshipCache_Case_01.id',
                '=',
                'id',
              ],
            ],
          ],
          'having' => [],
        ],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'SavedSearch_NYSS_Caseload_Overview_Details_SearchDisplay_NYSS_Caseload_Overview_Details_Table',
    'entity' => 'SearchDisplay',
    'cleanup' => 'unused',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'NYSS_Caseload_Overview_Details_Table',
        'label' => E::ts('NYSS Caseload - Overview Details Table'),
        'saved_search_id.name' => 'NYSS_Caseload_Overview_Details',
        'type' => 'table',
        'settings' => [
          'description' => E::ts(''),
          'sort' => [],
          'limit' => 10,
          'pager' => [],
          'placeholder' => 5,
          'columns' => [
            [
              'type' => 'html',
              'key' => 'id',
              'label' => E::ts('Case'),
              'sortable' => TRUE,
              'rewrite' => '<a href="/civicrm/contact/view/case?id=[id]&action=view&context=case&reset=1" target="_blank">#[id] &mdash; [subject]</a>',
            ],
            [
              'type' => 'field',
              'key' => 'GROUP_CONCAT_Case_CaseContact_Contact_01_sort_name',
              'label' => E::ts('Constituent(s)'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'case_type_id:label',
              'label' => E::ts('Case Type'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'status_id:label',
              'label' => E::ts('Status'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'start_date',
              'label' => E::ts('Start Date'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'GROUP_CONCAT_Case_CaseContact_Contact_01_Contact_RelationshipCache_Case_01_near_contact_id_display_name',
              'label' => E::ts('Case Manager(s)'),
              'sortable' => TRUE,
            ],
            [
              'text' => E::ts(''),
              'style' => 'default',
              'size' => 'btn-xs',
              'icon' => 'fa-bars',
              'links' => [
                [
                  'entity' => 'Case',
                  'action' => 'view',
                  'join' => '',
                  'target' => '',
                  'icon' => 'fa-external-link',
                  'text' => E::ts('View Case'),
                  'style' => 'default',
                  'path' => '',
                  'task' => '',
                  'conditions' => [],
                ],
                [
                  'task' => 'case.addRole',
                  'entity' => 'Case',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-user-plus',
                  'text' => E::ts('Case - Assign Role'),
                  'style' => 'default',
                  'path' => '',
                  'action' => '',
                  'conditions' => [],
                ],
                [
                  'task' => 'delete',
                  'entity' => 'Case',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-trash',
                  'text' => E::ts('Delete Cases'),
                  'style' => 'danger',
                  'path' => '',
                  'action' => '',
                  'conditions' => [],
                ],
              ],
              'type' => 'menu',
              'alignment' => 'text-right',
            ],
          ],
          'actions' => TRUE,
          'classes' => ['table', 'table-striped'],
          'actions_display_mode' => 'menu',
          'headerCount' => TRUE,
        ],
      ],
      'match' => [
        'saved_search_id',
        'name',
      ],
    ],
  ],
  [
    'name' => 'SavedSearch_NYSS_Caseload_Overview_Details_SearchDisplay_NyssCaseloadDetailsStats',
    'entity' => 'SearchDisplay',
    'cleanup' => 'unused',
    'update' => 'always',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'NyssCaseloadDetailsStats',
        'label' => E::ts('NYSS Caseload - Details Stats DB View'),
        'saved_search_id.name' => 'NYSS_Caseload_Overview_Details',
        'type' => 'entity',
        'settings' => [
          'entity_permission' => 'access caseload dashboard',
          'sort' => [],
          'columns' => [
            [
              'type' => 'field',
              'key' => 'id',
              'label' => E::ts('Case ID'),
              'spec' => [
                'name' => 'id',
                'data_type' => 'Integer',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'id',
                'original_field_entity' => 'Case',
                'entity_reference' => [
                  'entity' => 'Case',
                ],
                'input_type' => 'EntityRef',
              ],
            ],
            [
              'type' => 'field',
              'key' => 'segment_NYSS_Caseload_Open:label',
              'label' => E::ts('Open'),
              'spec' => [
                'name' => 'segment_NYSS_Caseload_Open',
                'data_type' => 'String',
                'suffixes' => ['id', 'label'],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'segment_NYSS_Caseload_Open',
                'original_field_entity' => 'Case',
                'input_type' => NULL,
                'entity_reference' => NULL,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'segment_NYSS_Caseload_Resolved:label',
              'label' => E::ts('Resolved'),
              'spec' => [
                'name' => 'segment_NYSS_Caseload_Resolved',
                'data_type' => 'String',
                'suffixes' => ['id', 'label'],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'segment_NYSS_Caseload_Resolved',
                'original_field_entity' => 'Case',
                'input_type' => NULL,
                'entity_reference' => NULL,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'Case_SK_NyssCaseloadUnassignedCases_id_01.segment_NYSS_Caseload_Unassigned:label',
              'label' => E::ts('Unassigned'),
              'spec' => [
                'name' => 'Case_SK_NyssCaseloadUnassignedCases_id_01_c7b0c6b4793bbbee',
                'data_type' => 'String',
                'suffixes' => ['id', 'label'],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'segment_NYSS_Caseload_Unassigned',
                'original_field_entity' => 'SK_NyssCaseloadUnassignedCases',
                'input_type' => NULL,
                'entity_reference' => NULL,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'segment_NYSS_Caseload_Urgent:label',
              'label' => E::ts('Urgent'),
              'spec' => [
                'name' => 'segment_NYSS_Caseload_Urgent',
                'data_type' => 'String',
                'suffixes' => ['id', 'label'],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'segment_NYSS_Caseload_Urgent',
                'original_field_entity' => 'Case',
                'input_type' => NULL,
                'entity_reference' => NULL,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'segment_NYSS_Caseload_Newer_Than_7_Days:label',
              'label' => E::ts('Open < 7 Days'),
              'spec' => [
                'name' => 'segment_NYSS_Caseload_Newer_Than_7_Days',
                'data_type' => 'String',
                'suffixes' => ['id', 'label'],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'segment_NYSS_Caseload_Newer_Than_7_Days',
                'original_field_entity' => 'Case',
                'input_type' => NULL,
                'entity_reference' => NULL,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'segment_NYSS_Caseload_Older_Than_7_Days:label',
              'label' => E::ts('Open > 7 Days'),
              'spec' => [
                'name' => 'segment_NYSS_Caseload_Older_Than_7_Days',
                'data_type' => 'String',
                'suffixes' => ['id', 'label'],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'segment_NYSS_Caseload_Older_Than_7_Days',
                'original_field_entity' => 'Case',
                'input_type' => NULL,
                'entity_reference' => NULL,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'segment_NYSS_Caseload_7_To_30_Days:label',
              'label' => E::ts('Open 7-30 Days'),
              'spec' => [
                'name' => 'segment_NYSS_Caseload_7_To_30_Days',
                'data_type' => 'String',
                'suffixes' => ['id', 'label'],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'segment_NYSS_Caseload_7_To_30_Days',
                'original_field_entity' => 'Case',
                'input_type' => NULL,
                'entity_reference' => NULL,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'segment_NYSS_Caseload_Older_Than_30_Days:label',
              'label' => E::ts('Open > 30 Days'),
              'spec' => [
                'name' => 'segment_NYSS_Caseload_Older_Than_30_Days',
                'data_type' => 'String',
                'suffixes' => ['id', 'label'],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'segment_NYSS_Caseload_Older_Than_30_Days',
                'original_field_entity' => 'Case',
                'input_type' => NULL,
                'entity_reference' => NULL,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'segment_NYSS_Caseload_Resolved_Last_7_Days:label',
              'label' => E::ts('Resolved Last 7 Days'),
              'spec' => [
                'name' => 'segment_NYSS_Caseload_Resolved_Last_7_Days',
                'data_type' => 'String',
                'suffixes' => ['id', 'label'],
                'options' => TRUE,
                'serialize' => NULL,
                'original_field_name' => 'segment_NYSS_Caseload_Resolved_Last_7_Days',
                'original_field_entity' => 'Case',
                'input_type' => NULL,
                'entity_reference' => NULL,
              ],
            ],
            [
              'type' => 'field',
              'key' => 'DATEDIFF_end_date_start_date',
              'label' => E::ts('Avg. Days to Resolution'),
              'spec' => [
                'name' => 'DATEDIFF_end_date_start_date',
                'data_type' => 'Integer',
                'suffixes' => NULL,
                'options' => FALSE,
                'serialize' => NULL,
                'original_field_name' => 'end_date',
                'original_field_entity' => 'Case',
                'input_type' => 'Number',
              ],
            ],
          ],
          'data_mode' => 'view',
        ],
      ],
      'match' => [
        'saved_search_id',
        'name',
      ],
    ],
  ],
];
