<?php
use CRM_NYSS_Reports_ExtensionUtil as E;

return [
  [
    'name' => 'SavedSearch_Contact_Tag_Search',
    'entity' => 'SavedSearch',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Contact_Tag_Search',
        'label' => E::ts('NYSS Constituent Tag Search'),
        'api_entity' => 'Contact',
        'api_params' => [
          'version' => 4,
          'select' => [
            'id',
            'sort_name',
            'contact_type:label',
            'contact_sub_type:label',
            'address_primary.city',
            'address_primary.street_address',
            'address_primary.postal_code',
            'address_primary.state_province_id:label',
            'email_primary.email',
            'Contact_Phone_contact_id_01.phone',
            'Contact_EntityTag_Tag_01.label',
          ],
          'orderBy' => [],
          'where' => [
            ['is_deleted', '=', FALSE],
          ],
          'groupBy' => [],
          'join' => [
            [
              'Tag AS Contact_EntityTag_Tag_01',
              'INNER',
              'EntityTag',
              [
                'id',
                '=',
                'Contact_EntityTag_Tag_01.entity_id',
              ],
              [
                'Contact_EntityTag_Tag_01.entity_table',
                '=',
                '\'civicrm_contact\'',
              ],
            ],
            [
              'Phone AS Contact_Phone_contact_id_01',
              'LEFT',
              [
                'id',
                '=',
                'Contact_Phone_contact_id_01.contact_id',
              ],
              [
                'Contact_Phone_contact_id_01.is_primary',
                '=',
                TRUE,
              ],
            ],
          ],
          'having' => [],
        ],
      ],
      'match' => ['name'],
    ],
  ],
  [
    'name' => 'SavedSearch_Contact_Tag_Search_SearchDisplay_Contact_Tag_Search_Table_1',
    'entity' => 'SearchDisplay',
    'cleanup' => 'unused',
    'update' => 'unmodified',
    'params' => [
      'version' => 4,
      'values' => [
        'name' => 'Contact_Tag_Search_Table_1',
        'label' => E::ts('Constituent Tag Search Table 1'),
        'saved_search_id.name' => 'Contact_Tag_Search',
        'type' => 'table',
        'settings' => [
          'description' => E::ts(NULL),
          'sort' => [
            ['sort_name', 'ASC'],
          ],
          'limit' => 50,
          'pager' => [],
          'placeholder' => 5,
          'columns' => [
            [
              'type' => 'field',
              'key' => 'contact_type:label',
              'dataType' => 'String',
              'label' => E::ts('Contact Type'),
              'sortable' => TRUE,
              'icons' => [
                [
                  'field' => 'contact_type:icon',
                  'side' => 'left',
                ],
              ],
            ],
            [
              'type' => 'field',
              'key' => 'sort_name',
              'dataType' => 'String',
              'label' => E::ts('Name'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'address_primary.street_address',
              'dataType' => 'String',
              'label' => E::ts('Street Address'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'address_primary.city',
              'dataType' => 'String',
              'label' => E::ts('City'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'address_primary.state_province_id:label',
              'dataType' => 'Integer',
              'label' => E::ts('State'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'address_primary.postal_code',
              'dataType' => 'String',
              'label' => E::ts('Postal Code'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'email_primary.email',
              'dataType' => 'String',
              'label' => E::ts('Email'),
              'sortable' => TRUE,
            ],
            [
              'type' => 'field',
              'key' => 'Contact_Phone_contact_id_01.phone',
              'dataType' => 'String',
              'label' => E::ts('Phone'),
              'sortable' => TRUE,
            ],
            [
              'text' => E::ts(''),
              'style' => 'default',
              'size' => 'btn-xs',
              'icon' => 'fa-bars',
              'links' => [
                [
                  'entity' => 'Contact',
                  'action' => 'view',
                  'join' => '',
                  'target' => '',
                  'icon' => 'fa-external-link',
                  'text' => E::ts('View Contact'),
                  'style' => 'default',
                  'path' => '',
                  'task' => '',
                  'condition' => [],
                ],
                [
                  'entity' => 'Contact',
                  'action' => 'update',
                  'join' => '',
                  'target' => '',
                  'icon' => 'fa-pencil',
                  'text' => E::ts('Update Contact'),
                  'style' => 'default',
                  'path' => '',
                  'task' => '',
                  'condition' => [],
                ],
                [
                  'entity' => 'Contact',
                  'action' => 'delete',
                  'join' => '',
                  'target' => 'crm-popup',
                  'icon' => 'fa-trash',
                  'text' => E::ts('Delete Contact'),
                  'style' => 'danger',
                  'path' => '',
                  'task' => '',
                  'condition' => [],
                ],
              ],
              'type' => 'menu',
              'alignment' => 'text-right',
            ],
          ],
          'actions' => [
            'contact.103',
            'download',
            'contact.mailing',
            'contact.9',
            'contact.107',
            'contact.2',
            'contact.1',
            'contact.16',
            'contact.3',
            'contact.6',
            'contact.108',
            'tag',
            'update',
          ],
          'classes' => ['table', 'table-striped'],
          'actions_display_mode' => 'menu',
          'headerCount' => TRUE,
          'editableRow' => [
            'disable' => TRUE,
          ],
        ],
      ],
      'match' => [
        'saved_search_id',
        'name',
      ],
    ],
  ],
];
