<?php /* Smarty version 2.6.26, created on 2010-08-24 15:26:12
         compiled from CRM/Report/Page/TemplateList.tpl */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('block', 'ts', 'CRM/Report/Page/TemplateList.tpl', 28, false),array('function', 'counter', 'CRM/Report/Page/TemplateList.tpl', 32, false),)), $this); ?>
<div class="crm-block crm-form-block crm-report-templateList-form-block">
<div class="help">
<?php $this->_tag_stack[] = array('ts', array()); $_block_repeat=true;smarty_block_ts($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?>Create reports for your users from any of the report templates listed below. Click on a template titles to get started. Click Existing Report(s) to see any reports that have already been created from that template.<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_ts($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?>
</div>
<?php echo ''; ?><?php if ($this->_tpl_vars['list']): ?><?php echo ''; ?><?php echo smarty_function_counter(array('start' => 0,'skip' => 1,'print' => false), $this);?><?php echo ''; ?><?php $_from = $this->_tpl_vars['list']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['report'] => $this->_tpl_vars['rows']):
?><?php echo '<div class="crm-accordion-wrapper crm-accordion_'; ?><?php echo $this->_tpl_vars['report']; ?><?php echo '-accordion crm-accordion_title-accordion crm-accordion-open"><div class="crm-accordion-header"><div class="icon crm-accordion-pointer"></div>'; ?><?php if ($this->_tpl_vars['report']): ?><?php echo ''; ?><?php if ($this->_tpl_vars['report'] == 'Contribute'): ?><?php echo ''; ?><?php $this->_tag_stack[] = array('ts', array()); $_block_repeat=true;smarty_block_ts($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php echo 'Contribution'; ?><?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_ts($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?><?php echo ''; ?><?php else: ?><?php echo ''; ?><?php echo $this->_tpl_vars['report']; ?><?php echo ''; ?><?php endif; ?><?php echo ''; ?><?php else: ?><?php echo 'Contact'; ?><?php endif; ?><?php echo ' Report Templates</div><!-- /.crm-accordion-header --><div class="crm-accordion-body"><div id="'; ?><?php echo $this->_tpl_vars['report']; ?><?php echo '" class="boxBlock"><table class="report-layout">'; ?><?php $_from = $this->_tpl_vars['rows']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['row']):
?><?php echo '<tr id="row_'; ?><?php echo smarty_function_counter(array(), $this);?><?php echo '" class="crm-report-templateList"><td class="crm-report-templateList-title" style="width:35%;"><a href="'; ?><?php echo $this->_tpl_vars['row']['url']; ?><?php echo '" title="'; ?><?php $this->_tag_stack[] = array('ts', array()); $_block_repeat=true;smarty_block_ts($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php echo 'Create report from this template'; ?><?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_ts($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?><?php echo '">&raquo; <strong>'; ?><?php echo $this->_tpl_vars['row']['title']; ?><?php echo '</strong></a>'; ?><?php if ($this->_tpl_vars['row']['instanceUrl']): ?><?php echo '<div style="font-size:10px;text-align:right;margin-top:3px;"><a href="'; ?><?php echo $this->_tpl_vars['row']['instanceUrl']; ?><?php echo '">'; ?><?php $this->_tag_stack[] = array('ts', array()); $_block_repeat=true;smarty_block_ts($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php echo 'Existing Report(s)'; ?><?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_ts($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?><?php echo '</a></div>'; ?><?php endif; ?><?php echo '</td><td style="cursor:help;" class="crm-report-templateList-description">'; ?><?php echo $this->_tpl_vars['row']['description']; ?><?php echo '</td></tr>'; ?><?php endforeach; endif; unset($_from); ?><?php echo '</table></div></div><!-- /.crm-accordion-body --></div><!-- /.crm-accordion-wrapper -->'; ?><?php endforeach; endif; unset($_from); ?><?php echo ''; ?><?php else: ?><?php echo '<div class="messages status"><div class="icon inform-icon"></div>&nbsp; '; ?><?php $this->_tag_stack[] = array('ts', array()); $_block_repeat=true;smarty_block_ts($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php echo 'There are currently no Report Templates.'; ?><?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_ts($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); ?><?php echo '</div>'; ?><?php endif; ?><?php echo ''; ?>


<?php echo '
<script type="text/javascript">
cj(function() {
   cj().crmaccordions(); 
});
</script>
'; ?>

</div>